/**
 * A股宏观看板 — 周更数据
 * ----------------------
 * 每周更新：修改下方 DASHBOARD_DATA，保存后刷新。
 * signal：green / yellow / red 为「对 A 股风险资产」的粗粒度提示，非买卖建议。
 * 存档：历史版本见 archive/ 目录。
 */
window.DASHBOARD_DATA = {
  meta: {
    title: "A股宏观看板",
    periodLabel: "2026年第19周",
    dataAsOf: "2026-05-10",
    nextUpdateDue: "2026-05-17",
    frequency: "周更",
    methodology: [
      "本周核心叙事：①FOMC 5月6-7日维持利率不变，措辞偏中性，市场解读为鸽派——美股大幅反弹（纳指100单周+5.5%）；②布伦特从$108回落至$101，美伊局势暂时降温；③A股温和跟涨，上证4,180；④美国5月12日CPI发布是本周最重要数据，验证关税通胀传导。",
      "中国月频数据：4月PMI、财新PMI已发布（请手动填入）；4月CPI/PPI预计5月中旬发布，本周或有数据。",
      "市场数据来源：yfinance实时抓取，截至2026年5月8日收盘。",
      "信号颜色规则：PMI>50→绿；VIX<20→黄；布伦特$100附近→黄（从$108回落）；DXY<98→黄偏正面。",
      "北向资金与全A成交额分位需手动查询东财数据中心。",
    ],
  },
  summary: {
    marketTheme:
      "FOMC鸽派解读·美股大涨：美联储5月6-7日维持利率不变，鲍威尔措辞中性偏鸽，市场大幅买入——纳指100单周涨超5%，SPX 7,399创新高；布伦特从$108回落至$101，油价压力阶段性缓解；A股温和上涨（上证4,180+1.6%）；黄金$4,731回归高位。本周三（5月12日）美国4月CPI发布，是验证关税通胀传导的关键数据。",
    riskAppetite: "偏乐观",
    riskAppetiteNote: "FOMC后市场情绪明显改善，纳指强势；但CPI数据将决定情绪能否持续",
    aShareView: "温和跟涨",
    aShareViewNote: "上证4,180（本周+1.6%），受美股带动，内需和科技板块领涨",
    usView:
      "标普500 7,399（创新高），纳指100 29,235（单周+5.5%），FOMC鸽派解读驱动。本周三5月12日CPI是关键——若通胀超预期，本周涨幅可能回吐。",
  },
  kpis: [
    {
      dim: "增长",
      name: "官方制造业 PMI（4月）",
      value: "50.3%",
      delta:
        "2026年4月（4/30发布）；较3月50.4%微降0.1pct，仍在荣枯线上方，关税冲击下制造业维持扩张，韧性超预期。重点关注新出口订单分项——是关税影响出口的直接验证指标。",
      signal: "green",
      updatedAt: "2026-04-30",
      source: "https://www.stats.gov.cn",
      sourceLabel: "国家统计局·4月PMI",
    },
    {
      dim: "增长",
      name: "财新制造业 PMI（4月）",
      value: "52.2%",
      delta:
        "2026年4月（4/29发布）；较官方PMI 50.3%高出1.9pct，中小民营企业景气度明显强于大型国企。官方与财新PMI双双扩张，增长信号双重确认，积极。",
      signal: "green",
      updatedAt: "2026-04-29",
      source: "https://www.pmi.caixin.com",
      sourceLabel: "财新PMI",
    },
    {
      dim: "通胀",
      name: "CPI 同比",
      value: "+0.9%（Q1均值）",
      delta:
        "Q1 2026均值+0.9%（4/17发布）；4月单月CPI尚未发布，预计5月12-15日公布。关税+布伦特$101双重背景下，4月读数走向值得关注。",
      signal: "yellow",
      updatedAt: "2026-04-17",
      source: "https://www.stats.gov.cn",
      sourceLabel: "国家统计局·Q1 CPI",
    },
    {
      dim: "通胀",
      name: "PPI 同比",
      value: "+0.5%（3月）",
      delta:
        "4月PPI尚未发布，预计与4月CPI同步（5月12-15日）。布伦特$101仍处百元以上，对上游工业品价格有支撑，4月PPI大概率维持正区间。",
      signal: "yellow",
      updatedAt: "2026-04-10",
      source: "https://www.stats.gov.cn",
      sourceLabel: "国家统计局·3月PPI",
    },
    {
      dim: "流动性",
      name: "DR007（月加权）",
      value: "1.44%（3月）",
      delta:
        "2026年3月月度加权均值1.44%，较2月1.49%环比下行5个基点（5bp）；央行持续宽松立场明确，资金面宽松对A股成长类估值正面。",
      signal: "green",
      updatedAt: "2026-03",
      source: "https://www.pbc.gov.cn",
      sourceLabel: "人民银行·市场运行",
    },
    {
      dim: "流动性",
      name: "10Y 国债收益率（中债）",
      value: "1.769%",
      delta:
        "较前期约1.80%继续小幅下行，债市需求旺盛，市场押注央行维持宽松；低收益率环境对A股成长类估值正面。",
      signal: "green",
      updatedAt: "2026-05-08",
      source: "https://cn.investing.com/rates-bonds/china-10-year-bond-yield",
      sourceLabel: "Investing.com·中债10Y",
    },
    {
      dim: "汇率",
      name: "USD/CNY",
      value: "约 7.20",
      delta:
        "美元持续走弱（DXY 97.8），人民币受支撑小幅升值；当前约7.20附近，较前期7.22略有升值。",
      signal: "green",
      updatedAt: "2026-05-08",
      source: "https://www.chinamoney.com.cn",
      sourceLabel: "外汇交易中心",
    },
    {
      dim: "市场",
      name: "南向资金（日净买入）",
      value: "131.7 亿元",
      delta:
        "5月8日：沪股通南向30.43亿 + 深股通南向101.26亿 = 合计131.7亿元净流入港股。南向资金持续流入港股，反映内地投资者对港股的配置意愿。注：北向资金（外资买A股）自2024年2月起停止每日披露。",
      signal: "green",
      updatedAt: "2026-05-08",
      source: "https://data.eastmoney.com/hsgt/hsgtV2.html",
      sourceLabel: "东方财富·沪深港通",
    },
    {
      dim: "市场",
      name: "全A成交额",
      value: "3.14 万亿元",
      delta:
        "5月7日沪深两市合计成交3.14万亿元（沪市1.36万亿+深市1.78万亿），较前一交易日缩量约829亿；FOMC决议日成交明显放量，市场情绪活跃，属近期高位水平。",
      signal: "green",
      updatedAt: "2026-05-07",
      source: "https://data.eastmoney.com/zjlx/detail.html",
      sourceLabel: "东方财富·资金流向",
    },
    {
      dim: "市场",
      name: "融资融券余额",
      value: "2.79 万亿元",
      delta:
        "融资（借钱买股）+融券（借股做空）合计余额；余额走高说明市场杠杆资金活跃，投资者信心改善。",
      signal: "green",
      updatedAt: "2026-05-08",
      source: "https://data.eastmoney.com/rzrq/total.html",
      sourceLabel: "东方财富·两融",
    },
    {
      dim: "增长",
      name: "工业增加值 YoY",
      value: "待核对",
      delta: "3月数据 4/17已发布 · 请查国家统计局官网",
      signal: "yellow",
      updatedAt: "2026-03",
      source: "https://www.stats.gov.cn",
      sourceLabel: "国家统计局",
    },
    {
      dim: "增长",
      name: "社零 YoY",
      value: "待核对",
      delta: "3月数据 4/17已发布 · 请查国家统计局官网",
      signal: "yellow",
      updatedAt: "2026-03",
      source: "https://www.stats.gov.cn",
      sourceLabel: "国家统计局",
    },
    {
      dim: "增长",
      name: "出口 YoY",
      value: "待核对",
      delta: "3月数据已发布（前值+21.8%）· 关税前抢出口效应",
      signal: "yellow",
      updatedAt: "2026-03",
      source: "http://www.customs.gov.cn",
      sourceLabel: "海关总署",
    },
    {
      dim: "增长",
      name: "地产开发投资 YoY",
      value: "待核对",
      delta: "Q1数据 4/17已发布（前值Q1 -11.1%）",
      signal: "red",
      updatedAt: "2026-Q1",
      source: "https://www.stats.gov.cn",
      sourceLabel: "国家统计局",
    },
    {
      dim: "流动性",
      name: "社融新增",
      value: "待核对",
      delta: "3月社融已发布（前值2月2.38万亿）· 信贷拐点关键观察",
      signal: "yellow",
      updatedAt: "2026-03",
      source: "https://www.pbc.gov.cn",
      sourceLabel: "央行",
    },
    {
      dim: "流动性",
      name: "贷款余额增速 YoY",
      value: "+6.0%",
      delta: "二十年新低（2月）· 信贷传导不畅 · 降准预期升温",
      signal: "red",
      updatedAt: "2026-02",
      source: "https://www.pbc.gov.cn",
      sourceLabel: "央行",
    },
  ],
  usKpis: [
    {
      dim: "增长",
      name: "非农就业",
      value: "+178K",
      delta: "↑（前值-133K，预期60K）· 失业率4.3% · 关税冲击尚未传导",
      signal: "green",
      updatedAt: "2026-03",
      source: "https://www.bls.gov",
      sourceLabel: "BLS",
    },
    {
      dim: "增长",
      name: "ISM制造业PMI",
      value: "52.7",
      delta: "↑0.3 · 连续3月扩张 · 4月数据或因关税走弱",
      signal: "green",
      updatedAt: "2026-03",
      source: "https://www.ismworld.org",
      sourceLabel: "ISM",
    },
    {
      dim: "增长",
      name: "ISM服务业PMI",
      value: "54.0",
      delta: "连续21月扩张 · 新订单60.6 · 暂未受关税直接冲击",
      signal: "green",
      updatedAt: "2026-03",
      source: "https://www.ismworld.org",
      sourceLabel: "ISM",
    },
    {
      dim: "增长",
      name: "零售销售 MoM",
      value: "待核对",
      delta: "3月数据 ~4/16发布（前值+0.6%）· 关税前消费者抢购效应？",
      signal: "yellow",
      updatedAt: "2026-03",
      source: "https://www.census.gov",
      sourceLabel: "Census",
    },
    {
      dim: "通胀",
      name: "CPI YoY",
      value: "3.3%",
      delta: "↑↑ 2024年5月以来最高（前值2.4%）· 油价回落或压制4月",
      signal: "red",
      updatedAt: "2026-03",
      source: "https://www.bls.gov",
      sourceLabel: "BLS",
    },
    {
      dim: "通胀",
      name: "核心PCE（Q1折年）",
      value: "4.3%",
      delta: "Q1 2026年化折率 · Fed最关注指标 · 关税传导显著",
      signal: "red",
      updatedAt: "2026-Q1",
      source: "https://www.bea.gov",
      sourceLabel: "BEA",
    },
    {
      dim: "利率",
      name: "联邦基金利率",
      value: "3.50–3.75%",
      delta: "连续2次维持 · 关税通胀 vs 增长下行 · 降息路径不确定",
      signal: "yellow",
      updatedAt: "2026-05-07",
      source: "https://www.federalreserve.gov",
      sourceLabel: "Fed",
    },
    {
      dim: "利率",
      name: "10Y Treasury DGS10",
      value: "4.41%",
      delta: "FOMC后从4.33%小幅反弹 · 5月12日CPI将是方向性决定因素",
      signal: "yellow",
      updatedAt: "2026-05-08",
      source: "https://fred.stlouisfed.org/series/DGS10",
      sourceLabel: "FRED",
    },
    {
      dim: "利率",
      name: "10Y TIPS 实际利率",
      value: "1.96%",
      delta: "仍高位 · 实际利率压制全球成长股估值",
      signal: "yellow",
      updatedAt: "2026-05-08",
      source: "https://fred.stlouisfed.org/series/DFII10",
      sourceLabel: "FRED",
    },
    {
      dim: "美元",
      name: "DXY 美元指数",
      value: "97.84",
      delta: "美元进一步走弱，DXY跌至97.8，创近期新低；对黄金、新兴市场和A股北向资金偏正面",
      signal: "green",
      updatedAt: "2026-05-08",
      source: "https://finance.yahoo.com/quote/DX-Y.NYB/",
      sourceLabel: "ICE",
    },
    {
      dim: "风险偏好",
      name: "VIX",
      value: "17.19",
      delta: "FOMC后维持平稳，市场情绪良好。本周三CPI数据若超预期，VIX可能出现跳升",
      signal: "yellow",
      updatedAt: "2026-05-08",
      source: "https://fred.stlouisfed.org/series/VIXCLS",
      sourceLabel: "CBOE",
    },
    {
      dim: "信用",
      name: "HY信用利差",
      value: "~420bp",
      delta: "↑ 较W15(294bp)大幅走阔 · 关税衰退担忧推升违约溢价",
      signal: "yellow",
      updatedAt: "2026-04-17",
      source: "https://fred.stlouisfed.org/series/BAMLH0A0HYM2",
      sourceLabel: "FRED",
    },
  ],
  framework: {
    growth: {
      title: "增长 Growth",
      metrics: ["官方PMI 50.3%（4月，双重确认扩张）", "财新PMI 52.2%（4月，中小民企强劲）", "A股上证 4,180（本周+1.6%）"],
      note: "官方PMI 50.3% + 财新PMI 52.2% 双双高于荣枯线，增长信号双重确认，积极。关税冲击下制造业韧性超预期。重点关注新出口订单分项是否跌破49，那是关税影响出口的直接信号。",
    },
    inflation: {
      title: "通胀 Inflation",
      metrics: ["CPI/PPI 4月数据待发布（本周）", "布伦特$101（从$108回落）", "⚠️ 美国5月12日CPI是本周关键"],
      note: "布伦特从$108回落至$101，通胀压力阶段性缓解。但美国5月12日CPI是本周最重要的全球数据——若关税通胀传导显现（超过3.5%），市场本周涨幅可能全部回吐，降息预期将再次推迟。",
    },
    liquidity: {
      title: "流动性 Liquidity",
      metrics: ["DR007 1.44%（3月，持续下行）", "DXY 97.84（美元创近期新低）", "FOMC维持利率，措辞偏鸽"],
      note: "本周流动性信号是四个支柱里最正面的——FOMC鸽派、DXY走弱、中国宽松持续三重利好。美债10Y收益率4.41%（TIPS实际利率1.96%），全球流动性环境边际改善明显。",
    },
    risk: {
      title: "风险偏好 Risk",
      metrics: ["VIX 17.19（平稳）", "纳指100 +5.5%（单周）", "黄金$4,731（回归高位）", "布伦特$101（从$108回落）"],
      note: "FOMC后风险偏好明显改善，纳指100单周涨超5%是强烈的risk-on信号。但黄金$4,731仍处历史高位，说明长期结构性不确定性未消——市场在短期乐观和长期谨慎之间保持分裂。本周CPI是情绪能否持续的关键测试。",
    },
  },
  aShare: {
    sectorsTop: [
      { name: "科技/半导体", note: "纳指强势带动，科技脱钩叙事+国产替代" },
      { name: "内需消费", note: "关税隔离+政策刺激，持续抗跌" },
      { name: "黄金/贵金属", note: "金价$4,731回归高位，板块强势" },
    ],
    sectorsBottom: [
      { name: "出口依赖制造业", note: "145%关税冲击持续，等待PMI实际验证" },
      { name: "航空/交通运输", note: "油价虽从$108回落，但$101仍高于年初" },
      { name: "地产链", note: "基本面修复缓慢，政策预期已部分定价" },
    ],
    flows: [
      {
        label: "南向净买入（5/8）",
        valueText: "131.7亿（沪30.4亿+深101.3亿）",
        bar: 65,
      },
      {
        label: "融资融券余额",
        valueText: "2.79万亿（融资为主）",
        bar: 70,
      },
      {
        label: "宽基ETF申赎",
        valueText: "净申购（国家队托底）",
        bar: 60,
      },
      {
        label: "全A成交（5/7）",
        valueText: "3.14万亿（放量活跃）",
        bar: 80,
      },
    ],
  },
  usMarket: [
    { label: "联邦基金目标区间", value: "3.50%–3.75%（5月6-7日维持不变，措辞偏鸽，市场积极解读）" },
    {
      label: "核心 PCE 同比",
      value: "约 3.1%（1月）；⚠️ 5月12日美国4月CPI是本周关键验证",
    },
    { label: "10Y 名义利率 DGS10", value: "4.41%（FRED: DGS10，5月8日）" },
    { label: "10Y TIPS（实际利率）", value: "1.96%（FRED: DFII10，5月8日）" },
    { label: "标普500 SPX", value: "7,399（本周+2.3%，创新高；YTD +7.9%）" },
    {
      label: "纳斯达克 IXIC / NDX",
      value: "26,247 / 29,235（NDX本周+5.5%，YTD纳指+13%，强势领涨）",
    },
    { label: "布伦特原油 Brent", value: "$101.3/桶（从$108回落，美伊局势暂时降温）" },
    { label: "黄金 XAU/USD", value: "$4,730.7/盎司（回归历史高位，DXY走弱驱动）" },
  ],
  scenarios: [
    {
      name: "基准",
      probability: "45%",
      text: "5月12日CPI温和（3.2-3.5%），降息预期维持年内1-2次；关税战僵局持续但市场已适应；A股温和震荡上行，上证4,100-4,400区间。",
    },
    {
      name: "乐观",
      probability: "30%",
      text: "CPI低于预期（<3.2%），降息路径前移；关税出现豁免信号；全球风险偏好持续改善，A股出口链和港股大幅反弹，上证冲击4,500+。",
    },
    {
      name: "悲观",
      probability: "25%",
      text: "CPI超预期上行（>3.8%，关税通胀传导显现）；美联储被迫偏鹰，本周涨幅全部回吐；VIX重回25+，A股受外部压力回调。",
    },
  ],
  watchlist: [
    {
      title: "⚠️ 美国 4月 CPI（5月12日，本周三）",
      condition: "CPI同比是否超预期上行（市场预期约3.4%）",
      action: "低于预期→降息预期进一步前移，美股续涨，A股跟涨；超预期→本周涨幅回吐，VIX跳升，美联储偏鹰",
      source: "BLS（5月12日北京时间20:30）",
    },
    {
      title: "⚠️ 4月PMI新出口订单（已发布，待填入）",
      condition: "新出口订单是否跌破49",
      action: "跌破49→关税冲击确认传导；守住50→制造业韧性超预期",
      source: "国家统计局（已发布4/30，请手动更新）",
    },
    {
      title: "中国 4月 CPI/PPI（本周发布）",
      condition: "CPI是否继续温和；PPI是否守住正区间",
      action: "PPI转负→再通缩压力，中上游利润预期下修；温和正区间→宽松政策空间维持",
      source: "国家统计局（5月12日前后）",
    },
    {
      title: "布伦特油价方向",
      condition: "是否重回$108+（美伊局势再度紧张）或跌破$95",
      action: "重回$108+→通胀压力重燃，FOMC鸽派解读被修正；跌破$95→通胀压力大幅缓解，降息路径前移",
      source: "财经终端 / yfinance",
    },
    {
      title: "关税谈判信号",
      condition: "中美任何官方层面接触，或部分商品豁免公告",
      action: "关键市场反转触发器；出口链与港股弹性最大",
      source: "商务部/USTR官网，财联社",
    },
    {
      title: "VIX 跳升",
      condition: "VIX > 22（当前17.19，若CPI超预期可能触发）",
      action: "风险资产快速回调信号；关注A股北向当日流出",
      source: "yfinance ^VIX",
    },
    {
      title: "央行政策对冲",
      condition: "降准或非对称降息正式宣布",
      action: "流动性宽松兑现；债市直接受益，成长类估值提振",
      source: "人民银行",
    },
  ],
};
