/**
 * A股宏观看板 — 周更数据
 * ----------------------
 * 每周更新：修改下方 DASHBOARD_DATA，保存后刷新。
 * signal：green / yellow / red 为「对 A 股风险资产」的粗粒度提示，非买卖建议。
 * 存档：历史版本见 archive/ 目录。
 */
window.DASHBOARD_DATA = {
  meta: {
    title: "A股宏观看板",
    periodLabel: "2026年第23周",
    weekNumber: "W23",
    weekThemeShort: "非农炸弹·美股闪崩·油价暴跌",
    dataAsOf: "2026-06-05",
    nextUpdateDue: "2026-06-14",
    frequency: "周更",
    alertBanner: "⚠️ 本周关键：6月非农数据远超预期（6/5发布），市场「好消息=坏消息」——降息预期彻底熄灭；NDX单日暴跌-4.8%，VIX从15飙升至21.5（+40%）；SPX从7,609峰值闪崩至7,383（-3.0%）。但布伦特暴跌至$93（较W20的$109跌15%），伊朗局势显著缓和。A股持续阴跌至4,028（-2.6%）。",
    methodology: [
      "本周核心叙事：①6月5日（周五）非农就业数据远超预期，劳动力市场过热→降息预期彻底熄灭→美股闪崩；②NDX单日-4.8%（30,660→28,957），VIX暴涨40%至21.5；③布伦特从$109（W20）暴跌至$93（-15%），伊朗局势显著降温；④DXY突破100，美元走强压制新兴市场；⑤A股持续阴跌，上证跌至4,028。",
      "注意：本期跳过W21/W22，直接从W20更新至W23。W21-W22期间美股持续上涨（SPX一度触7,609，NDX破30,000），油价大幅回落，市场情绪乐观——直到周五非农炸弹。",
      "市场数据来源：yfinance实时抓取，截至2026年6月5日收盘。",
      "信号颜色规则：VIX 21.5→红；NDX单日-4.8%→红；DXY>100→黄；布伦特$93（从$109暴跌）→绿转中。",
      "北向资金与全A成交额分位需手动查询东财数据中心。",
    ],
  },
  summary: {
    marketTheme:
      "非农炸弹·美股闪崩：6/5非农数据远超预期，劳动力市场过热→「好消息=坏消息」→降息彻底熄灭。NDX从30,660暴跌至28,957（单日-4.8%），VIX从15.4飙升至21.5（+40%），SPX从7,609峰值闪崩至7,383。但布伦特暴跌至$93（较3周前$109跌15%，伊朗局势降温），通胀压力边际缓解。A股持续阴跌至4,028（-2.6%）。",
    riskAppetite: "急剧恶化",
    riskAppetiteNote: "VIX单日暴涨40%至21.5，NDX单日-4.8%，非农打破降息叙事",
    aShareView: "持续阴跌",
    aShareViewNote: "上证4,028（较W20 -2.6%），内外部压力共振，但油价暴跌缓解PPI压力",
    usView:
      "SPX 7,383（从7,609峰值闪崩-3.0%），NDX 28,957（单日-4.8%）。6/5非农超预期→降息预期熄灭→成长股遭抛售。DXY突破100。但油价暴跌至$93是正面信号。下周6/10 FOMC会议是关键。",
  },
  kpis: [
    {
      dim: "增长",
      name: "官方制造业 PMI（5月）",
      value: "50.3%",
      delta:
        "5月PMI预计5月底发布，请查国家统计局。4月PMI 50.3%仍在荣枯线上方。",
      signal: "green",
      updatedAt: "2026-04-30",
      source: "https://www.stats.gov.cn",
      sourceLabel: "国家统计局",
    },
    {
      dim: "增长",
      name: "财新制造业 PMI（5月）",
      value: "52.2%",
      delta:
        "5月财新PMI待发布。4月52.2%显示中小民企景气度强劲。",
      signal: "green",
      updatedAt: "2026-04-29",
      source: "https://www.pmi.caixin.com",
      sourceLabel: "财新PMI",
    },
    {
      dim: "通胀",
      name: "CPI 同比（4月）",
      value: "+1.2%",
      delta:
        "4月CPI +1.2%。5月CPI预计6月中旬发布。油价从$109暴跌至$93，5月CPI可能回落。",
      signal: "green",
      updatedAt: "2026-05-11",
      source: "https://www.stats.gov.cn",
      sourceLabel: "国家统计局·4月CPI",
    },
    {
      dim: "通胀",
      name: "PPI 同比（4月）",
      value: "+2.8%",
      delta:
        "4月PPI +2.8%受油价驱动。但布伦特从$109暴跌至$93（-15%），5月PPI大概率显著回落，上游利润预期下修。",
      signal: "yellow",
      updatedAt: "2026-05-11",
      source: "https://www.stats.gov.cn",
      sourceLabel: "国家统计局·4月PPI",
    },
    {
      dim: "流动性",
      name: "DR007（月加权）",
      value: "1.44%（3月）",
      delta:
        "央行持续宽松立场明确。A股持续阴跌背景下，降准预期升温。",
      signal: "green",
      updatedAt: "2026-03",
      source: "https://www.pbc.gov.cn",
      sourceLabel: "人民银行·市场运行",
    },
    {
      dim: "流动性",
      name: "10Y 国债收益率（中债）",
      value: "~1.75%",
      delta:
        "中债低位震荡。中美利差（DGS10 4.54% vs 中债~1.75%）约279bp，资本流出压力持续。",
      signal: "green",
      updatedAt: "2026-06-05",
      source: "https://cn.investing.com/rates-bonds/china-10-year-bond-yield",
      sourceLabel: "Investing.com·中债10Y",
    },
    {
      dim: "汇率",
      name: "USD/CNY",
      value: "约 7.25",
      delta:
        "DXY突破100，美元走强，人民币承压。央行维稳意图明确但压力增大。",
      signal: "yellow",
      updatedAt: "2026-06-05",
      source: "https://www.chinamoney.com.cn",
      sourceLabel: "外汇交易中心",
    },
    {
      dim: "市场",
      name: "南向资金（日净买入）",
      value: "待更新",
      delta: "请查东方财富沪深港通数据。",
      signal: "yellow",
      updatedAt: "2026-06-05",
      source: "https://data.eastmoney.com/hsgt/hsgtV2.html",
      sourceLabel: "东方财富·沪深港通",
    },
    {
      dim: "市场",
      name: "全A成交额",
      value: "待更新",
      delta: "请查东方财富更新。",
      signal: "yellow",
      updatedAt: "2026-06-05",
      source: "https://data.eastmoney.com/zjlx/detail.html",
      sourceLabel: "东方财富·资金流向",
    },
    {
      dim: "市场",
      name: "融资融券余额",
      value: "待更新",
      delta: "请查东方财富更新。",
      signal: "yellow",
      updatedAt: "2026-06-05",
      source: "https://data.eastmoney.com/rzrq/total.html",
      sourceLabel: "东方财富·两融",
    },
    {
      dim: "增长",
      name: "工业增加值 YoY",
      value: "待核对",
      delta: "4月数据应已发布 · 请查国家统计局官网",
      signal: "yellow",
      updatedAt: "2026-04",
      source: "https://www.stats.gov.cn",
      sourceLabel: "国家统计局",
    },
    {
      dim: "增长",
      name: "社零 YoY",
      value: "待核对",
      delta: "4月数据应已发布 · 请查国家统计局官网",
      signal: "yellow",
      updatedAt: "2026-04",
      source: "https://www.stats.gov.cn",
      sourceLabel: "国家统计局",
    },
    {
      dim: "增长",
      name: "出口 YoY",
      value: "待核对",
      delta: "4月数据应已发布 · 关税冲击是否开始显现",
      signal: "yellow",
      updatedAt: "2026-04",
      source: "http://www.customs.gov.cn",
      sourceLabel: "海关总署",
    },
    {
      dim: "增长",
      name: "地产开发投资 YoY",
      value: "待核对",
      delta: "1-4月累计数据应已发布",
      signal: "red",
      updatedAt: "2026-Q1",
      source: "https://www.stats.gov.cn",
      sourceLabel: "国家统计局",
    },
    {
      dim: "流动性",
      name: "社融新增",
      value: "待核对",
      delta: "4月社融应已发布",
      signal: "yellow",
      updatedAt: "2026-04",
      source: "https://www.pbc.gov.cn",
      sourceLabel: "央行",
    },
    {
      dim: "流动性",
      name: "贷款余额增速 YoY",
      value: "+6.0%",
      delta: "二十年新低（2月）· 信贷传导不畅 · 降准预期升温",
      signal: "red",
      updatedAt: "2026-02",
      source: "https://www.pbc.gov.cn",
      sourceLabel: "央行",
    },
  ],
  usKpis: [
    {
      dim: "增长",
      name: "非农就业（5月）",
      value: "超预期（6/5发布）",
      delta: "↑↑ 远超预期！劳动力市场过热，「好消息=坏消息」——直接触发NDX -4.8%闪崩、VIX +40%暴涨。降息预期彻底熄灭。",
      signal: "red",
      updatedAt: "2026-06-05",
      source: "https://www.bls.gov",
      sourceLabel: "BLS·5月就业",
    },
    {
      dim: "增长",
      name: "ISM制造业PMI",
      value: "52.7",
      delta: "3月数据 · 5月数据待更新",
      signal: "green",
      updatedAt: "2026-03",
      source: "https://www.ismworld.org",
      sourceLabel: "ISM",
    },
    {
      dim: "增长",
      name: "ISM服务业PMI",
      value: "54.0",
      delta: "3月数据 · 5月数据待更新",
      signal: "green",
      updatedAt: "2026-03",
      source: "https://www.ismworld.org",
      sourceLabel: "ISM",
    },
    {
      dim: "通胀",
      name: "CPI YoY（4月）",
      value: "3.8%",
      delta: "4月超预期（前值3.3%）· 5月CPI 6/11发布——油价暴跌可能压低读数 · FOMC前最后一个关键数据",
      signal: "red",
      updatedAt: "2026-05-12",
      source: "https://www.bls.gov/news.release/cpi.nr0.htm",
      sourceLabel: "BLS·4月CPI",
    },
    {
      dim: "通胀",
      name: "核心CPI YoY（4月）",
      value: "2.8%",
      delta: "服务业通胀顽固 · 核心环比+0.4%",
      signal: "red",
      updatedAt: "2026-05-12",
      source: "https://www.bls.gov/news.release/cpi.nr0.htm",
      sourceLabel: "BLS·核心CPI",
    },
    {
      dim: "通胀",
      name: "核心PCE（Q1折年）",
      value: "4.3%",
      delta: "Q1 2026年化折率 · Fed最关注指标",
      signal: "red",
      updatedAt: "2026-Q1",
      source: "https://www.bea.gov",
      sourceLabel: "BEA",
    },
    {
      dim: "利率",
      name: "联邦基金利率",
      value: "3.50–3.75%",
      delta: "维持不变 · ⚠️ 下周6/10 FOMC会议！非农超预期后鹰派措辞几乎确定",
      signal: "red",
      updatedAt: "2026-04-29",
      source: "https://www.federalreserve.gov",
      sourceLabel: "Fed",
    },
    {
      dim: "利率",
      name: "10Y Treasury DGS10",
      value: "4.54%",
      delta: "从W20的4.59%小幅回落（油价暴跌压低通胀预期），但非农后周五盘中一度冲高。FOMC后方向待定。",
      signal: "yellow",
      updatedAt: "2026-06-05",
      source: "https://fred.stlouisfed.org/series/DGS10",
      sourceLabel: "FRED",
    },
    {
      dim: "利率",
      name: "10Y TIPS 实际利率",
      value: "~2.05%",
      delta: "实际利率仍高位，压制全球成长股估值",
      signal: "red",
      updatedAt: "2026-06-05",
      source: "https://fred.stlouisfed.org/series/DFII10",
      sourceLabel: "FRED",
    },
    {
      dim: "美元",
      name: "DXY 美元指数",
      value: "100.07",
      delta: "↑ 突破100关口！非农超预期+降息熄灭→美元走强。对新兴市场和黄金压力加大。",
      signal: "red",
      updatedAt: "2026-06-05",
      source: "https://finance.yahoo.com/quote/DX-Y.NYB/",
      sourceLabel: "ICE",
    },
    {
      dim: "风险偏好",
      name: "VIX",
      value: "21.51",
      delta: "↑↑ 从15.4暴涨至21.5（+40%），非农数据触发恐慌抛售。接近22警戒线。",
      signal: "red",
      updatedAt: "2026-06-05",
      source: "https://fred.stlouisfed.org/series/VIXCLS",
      sourceLabel: "CBOE",
    },
    {
      dim: "信用",
      name: "HY信用利差",
      value: "~420bp",
      delta: "维持高位 · 非农闪崩后可能进一步走阔",
      signal: "yellow",
      updatedAt: "2026-04-17",
      source: "https://fred.stlouisfed.org/series/BAMLH0A0HYM2",
      sourceLabel: "FRED",
    },
  ],
  framework: {
    growth: {
      title: "增长 Growth",
      metrics: ["美国非农超预期（经济过热）", "中国PMI待更新（5月数据）", "上证4,028（持续阴跌-2.6%）"],
      note: "美国经济「过热」成了问题——非农远超预期意味着劳动力市场太紧，美联储无法降息。对A股而言，外部流动性收紧+内部增长动能不足双重压力。油价暴跌对中国制造业成本端是正面的。",
    },
    inflation: {
      title: "通胀 Inflation",
      metrics: ["布伦特暴跌$109→$93（-15%！伊朗局势缓和）", "美国CPI 3.8%（4月，5月待发布）", "5月CPI 6/11发布（FOMC前关键数据）"],
      note: "通胀出现分化信号：油价暴跌15%是过去3周最大的正面变化，将显著压低5月CPI能源分项。但非农过热意味着服务业通胀（工资→物价）仍顽固。6/11 CPI是FOMC前最后一个关键数据——若油价拖动整体CPI回落，可能缓和鹰派措辞。",
    },
    liquidity: {
      title: "流动性 Liquidity",
      metrics: ["DXY突破100（美元走强）", "DGS10 4.54%（小幅回落）", "VIX 21.5（恐慌水位）"],
      note: "全球流动性环境恶化。DXY突破100是关键心理关口——美元强势压制新兴市场资金流和大宗商品。VIX暴涨至21.5接近22警戒线。但DGS10从4.59%小幅回落至4.54%（油价暴跌压低通胀预期），是唯一的边际正面信号。中国国内流动性仍宽松。",
    },
    risk: {
      title: "风险偏好 Risk",
      metrics: ["VIX 21.5（+40%单日暴涨！）", "NDX单日-4.8%（闪崩）", "黄金$4,337（-4.9%）", "布伦特$93（-15%，伊朗缓和）"],
      note: "风险偏好急剧恶化。周一至周四市场还沉浸在乐观中（SPX触7,609新高），周五非农一记重锤。NDX单日-4.8%是今年最大单日跌幅之一。VIX暴涨40%。黄金也跌4.9%（美元太强）。唯一安慰是油价暴跌意味着地缘风险在降低。",
    },
  },
  aShare: {
    indices: [
      { name: "上证综指", value: "4,027.7", change: "-2.6%", direction: "down" },
      { name: "深证成指", value: "15,315", change: "-1.6%", direction: "down" },
      { name: "创业板指", value: "3,958", change: "-3.1%", direction: "down" },
      { name: "沪深300", value: "4,817", change: "-0.9%", direction: "down" },
    ],
    sectorsTop: [
      { name: "公用事业/电力", note: "防御属性突出，市场下跌时资金避风港" },
      { name: "银行/保险", note: "低估值高股息，防御性配置" },
      { name: "内需消费", note: "关税隔离+CPI温和，内需板块相对抗跌" },
    ],
    sectorsBottom: [
      { name: "上游材料/能源", note: "油价从$109暴跌至$93，上游利润预期大幅下修" },
      { name: "出口依赖制造业", note: "关税145%未变+美元走强双重压力" },
      { name: "成长/科技", note: "全球科技股闪崩传导，VIX暴涨压制风险偏好" },
    ],
    flows: [
      { label: "南向净买入", valueText: "待更新（请查东财数据）", bar: 45 },
      { label: "融资融券余额", valueText: "待更新", bar: 50 },
      { label: "宽基ETF申赎", valueText: "待观察（国家队动态）", bar: 55 },
      { label: "全A成交", valueText: "待更新", bar: 50 },
    ],
  },
  usMarket: [
    { label: "联邦基金目标区间", value: "3.50%–3.75%（维持不变）· ⚠️ 下周6/10 FOMC！" },
    { label: "CPI 同比（4月）", value: "3.8% · 5月CPI 6/11发布（FOMC前关键数据，油价暴跌或压低读数）" },
    { label: "核心 PCE 同比（Q1折年）", value: "4.3%（关税传导显著）" },
    { label: "10Y 名义利率 DGS10", value: "4.54%（从4.59%小幅回落，油价暴跌压低通胀预期）" },
    { label: "10Y TIPS（实际利率）", value: "~2.05%（仍高位，压制成长股估值）" },
    { label: "标普500 SPX", value: "7,383（从7,609峰值闪崩-3.0%；非农周五重锤）" },
    { label: "纳斯达克 IXIC / NDX", value: "25,709 / 28,957（NDX单日-4.8%闪崩！）" },
    { label: "布伦特原油 Brent", value: "$93.1/桶（从$109暴跌-15%！伊朗局势显著缓和）" },
    { label: "黄金 XAU/USD", value: "$4,337/盎司（-4.9%，DXY破100+美债利率压制）" },
    { label: "DXY 美元指数", value: "100.07（突破100！非农超预期→降息熄灭→美元强势）" },
  ],
  usMarketAssets: [
    { name: "S&P 500", value: "7,383", wow: "-2.6%", wowDir: "down", note: "周五非农闪崩，从7,609峰值坠落" },
    { name: "Nasdaq / NDX", value: "25,709 / 28,957", wow: "-4.5%", wowDir: "down", note: "NDX单日-4.8%！今年最大跌幅" },
    { name: "Russell 2000", value: "~1,720", wow: "-3%", wowDir: "down", note: "小盘股遭重创" },
    { name: "黄金 XAU/USD", value: "$4,337", wow: "-4.9%", wowDir: "down", note: "DXY破100+利率高位压制" },
    { name: "布伦特原油", value: "$93.1/桶", wow: "+1.1%", wowDir: "neutral", note: "较W20暴跌-15%（伊朗缓和）" },
  ],
  usContext: {
    styleNote: "全面下跌 · 成长重创（NDX -4.8%）> 价值 > 防御 · 现金为王",
    sectorNote: "科技/成长遭重创 · 能源随油价暴跌 · 公用事业/必需消费相对抗跌",
    narrative: [
      { title: "① 非农炸弹（本周核心）", text: "6月5日（周五）发布的5月非农就业数据远超预期，劳动力市场过热。「好消息=坏消息」——经济太好意味着美联储没有理由降息。市场瞬间重新定价：降息预期彻底熄灭，NDX单日-4.8%，VIX暴涨40%至21.5。" },
      { title: "② 油价暴跌（正面信号）", text: "布伦特从W20的$109暴跌至$93（-15%），伊朗局势显著缓和。这是过去3周最重要的正面变化——将压低5月CPI能源分项，可能给美联储一些回旋空间。" },
      { title: "③ FOMC在即（下周6/10）", text: "下周二三FOMC会议是本轮行情的关键节点。非农过热+CPI高位→鹰派措辞几乎确定。但油价暴跌如果拉低5月CPI（6/11发布），可能避免最坏情境。" },
      { title: "④ 贸易战", text: "关税145%/125%格局未变。峰会后续落实有限。美元走强+DXY>100对中国出口额外施压。" },
    ],
  },
  drivers: [
    { rank: 1, name: "FOMC会议（6/10-11）", detail: "下周！非农超预期后鹰派几乎确定<br><strong>阈值：</strong>措辞偏鹰→市场继续下跌 / 意外鸽派→大幅反弹<br><strong>影响：</strong>全球利率锚、美股方向、新兴市场" },
    { rank: 2, name: "5月CPI（6/11发布）", detail: "FOMC前最后一个关键通胀数据<br><strong>阈值：</strong><3.5%→降息重现希望 / >3.8%→鹰派加码<br><strong>影响：</strong>DGS10方向、成长股估值" },
    { rank: 3, name: "非农后续影响", detail: "VIX 21.5接近22警戒线<br><strong>阈值：</strong>VIX>25→恐慌蔓延 / <18→修复<br><strong>影响：</strong>风险资产全线" },
    { rank: 4, name: "油价走势", detail: "布伦特$93（从$109暴跌-15%）<br><strong>阈值：</strong><$85→通胀大幅缓解 / 反弹>$100→压力重燃<br><strong>影响：</strong>CPI、PPI、美联储路径" },
    { rank: 5, name: "DXY美元走势", detail: "突破100关口<br><strong>阈值：</strong>>102→新兴市场资金大幅流出 / <99→压力缓解<br><strong>影响：</strong>人民币、北向资金、A股外资" },
  ],
  scenarios: [
    {
      name: "基准",
      probability: "45%",
      text: "FOMC鹰派但不加码（维持利率+鹰派措辞）；5月CPI因油价回落小幅改善至3.5%左右；市场消化非农冲击后横盘；A股上证3,900-4,100区间震荡。",
    },
    {
      name: "乐观",
      probability: "20%",
      text: "5月CPI大幅低于预期（<3.3%，油价暴跌传导）；FOMC措辞意外中性；降息预期重现；美股V型反弹，NDX收复30,000；A股跟涨至4,200+。",
    },
    {
      name: "悲观",
      probability: "35%",
      text: "FOMC偏鹰+暗示不排除加息；5月CPI仍高（>3.8%）；VIX突破25；NDX继续下探28,000以下；DXY>102；A股受外溢效应跌破3,900。",
    },
  ],
  watchlist: [
    {
      title: "⚠️ FOMC会议（6/10-11，下周！）",
      condition: "利率决议+鲍威尔措辞：鹰派程度如何",
      action: "维持+偏鹰→继续承压但可控；暗示加息→恐慌加剧；意外鸽派→大反弹",
      source: "Fed官网 / 北京时间6/12凌晨2:00",
    },
    {
      title: "⚠️ 5月CPI（6/11发布，FOMC次日）",
      condition: "整体CPI是否因油价暴跌回落至3.5%以下",
      action: "<3.3%→降息叙事重启，美股反弹；>3.8%→通胀顽固确认，继续下跌",
      source: "BLS（北京时间6/11晚20:30）",
    },
    {
      title: "VIX走势（当前21.5）",
      condition: "是否突破25（恐慌蔓延）或回落至18以下（修复）",
      action: ">25→风险资产快速回调，减仓信号；<18→恐慌消化，可考虑抄底",
      source: "yfinance ^VIX",
    },
    {
      title: "DXY美元走势（当前100.07）",
      condition: "是否持续走强>102或回落<99",
      action: ">102→新兴市场资金流出加速，A股外资压力；<99→压力缓解",
      source: "yfinance DX-Y.NYB",
    },
    {
      title: "油价是否持续回落",
      condition: "布伦特是否跌破$85或反弹至$100+",
      action: "<$85→通胀大幅缓解，降息路径前移；>$100→通胀压力重燃",
      source: "yfinance BZ=F",
    },
    {
      title: "央行政策对冲（降准/降息）",
      condition: "A股持续阴跌+外部压力→央行是否出手",
      action: "降准落地=流动性宽松信号，A股短期提振",
      source: "人民银行",
    },
  ],
};
