/**
 * A股宏观看板 — 周更数据
 * ----------------------
 * 每周更新：修改下方 DASHBOARD_DATA，保存后刷新。
 * signal：green / yellow / red 为「对 A 股风险资产」的粗粒度提示，非买卖建议。
 * 存档：历史版本见 archive/ 目录。
 */
window.DASHBOARD_DATA = {
  meta: {
    title: "A股宏观看板",
    periodLabel: "2026年第20周",
    weekNumber: "W20",
    weekThemeShort: "通胀回归·油价飙升",
    dataAsOf: "2026-05-15",
    nextUpdateDue: "2026-05-24",
    frequency: "周更",
    alertBanner: "⚠️ 本周关键：美国4月CPI 3.8%超预期（关税通胀传导确认）；布伦特重回$109（伊朗/霍尔木兹局势再升温）；DGS10飙升至4.59%（+18bp）；特朗普-习近平峰会声势大实质少。SPX周中创7,517纪录后回落至7,408，A股-1.1%至4,135。",
    methodology: [
      "本周核心叙事：①美国4月CPI 3.8%超预期（前值3.3%），关税通胀传导确认——DGS10飙升至4.59%；②布伦特重回$109（伊朗/霍尔木兹海峡紧张再升温）；③特朗普-习近平北京峰会（5/14-15），声势大实质少，市场反应平淡；④SPX周内创纪录7,517后回落至7,408，A股回调至4,135。",
      "中国月频数据：4月CPI +1.2%、PPI +2.8%已发布（5/11），PPI大幅跳升受油价驱动。",
      "市场数据来源：yfinance实时抓取，截至2026年5月15日收盘。",
      "信号颜色规则：CPI 3.8%超预期→红；VIX 18.4→黄；布伦特$109创新高→红；DXY 99.3反弹→黄。",
      "北向资金与全A成交额分位需手动查询东财数据中心。",
    ],
  },
  summary: {
    marketTheme:
      "通胀回归·油价飙升·峰会雷声大雨点小：4月CPI 3.8%创一年新高，确认关税通胀传导——DGS10从4.41%升至4.59%，降息预期进一步推迟；布伦特重回$109（伊朗局势再度紧张）；特朗普-习近平北京峰会（5/14-15）声势浩大但实质成果有限，市场反应平淡；SPX周中创纪录7,517后周五大跌收7,408；A股受油价和通胀预期拖累回调至4,135（-1.1%）。",
    riskAppetite: "偏谨慎",
    riskAppetiteNote: "CPI超预期+油价飙升双重压力，降息预期推迟，短期风险偏好回落",
    aShareView: "震荡偏弱",
    aShareViewNote: "上证4,135（本周-1.1%），油价推高PPI但内需消费尚可，结构分化",
    usView:
      "标普500 7,408（周中创纪录7,517后回落），纳指100 29,125（-0.4%）。CPI 3.8%超预期+布伦特$109，DGS10升至4.59%，通胀回归压制估值。峰会未带来实质关税缓解。",
  },
  kpis: [
    {
      dim: "增长",
      name: "官方制造业 PMI（4月）",
      value: "50.3%",
      delta:
        "2026年4月（4/30发布）；较3月50.4%微降0.1pct，仍在荣枯线上方，关税冲击下制造业维持扩张，韧性超预期。新出口订单分项需关注。",
      signal: "green",
      updatedAt: "2026-04-30",
      source: "https://www.stats.gov.cn",
      sourceLabel: "国家统计局·4月PMI",
    },
    {
      dim: "增长",
      name: "财新制造业 PMI（4月）",
      value: "52.2%",
      delta:
        "2026年4月（4/29发布）；较官方PMI 50.3%高出1.9pct，中小民营企业景气度明显强于大型国企。官方与财新双双扩张，增长信号双重确认。",
      signal: "green",
      updatedAt: "2026-04-29",
      source: "https://www.pmi.caixin.com",
      sourceLabel: "财新PMI",
    },
    {
      dim: "通胀",
      name: "CPI 同比（4月）",
      value: "+1.2%",
      delta:
        "4月CPI同比+1.2%（5/11发布），较Q1均值+0.9%小幅上行。食品-1.6%，非食品+1.8%（油价推动）。核心CPI（剔除食品能源）+1.2%。温和通胀，政策空间充裕。",
      signal: "green",
      updatedAt: "2026-05-11",
      source: "https://www.stats.gov.cn/sj/zxfb/202605/t20260511_1963659.html",
      sourceLabel: "国家统计局·4月CPI",
    },
    {
      dim: "通胀",
      name: "PPI 同比（4月）",
      value: "+2.8%",
      delta:
        "4月PPI同比+2.8%（5/11发布），较3月+0.5%大幅跳升！环比+1.7%。国际油价飙升（布伦特$109）+大宗商品价格上涨是主因。上游材料能源板块利润预期改善，但也传导成本压力。",
      signal: "yellow",
      updatedAt: "2026-05-11",
      source: "https://www.stats.gov.cn/sj/zxfbhjd/202605/t20260511_1963657.html",
      sourceLabel: "国家统计局·4月PPI",
    },
    {
      dim: "流动性",
      name: "DR007（月加权）",
      value: "1.44%（3月）",
      delta:
        "2026年3月月度加权均值1.44%，较2月1.49%环比下行5bp；央行持续宽松立场明确，资金面宽松对A股成长类估值正面。",
      signal: "green",
      updatedAt: "2026-03",
      source: "https://www.pbc.gov.cn",
      sourceLabel: "人民银行·市场运行",
    },
    {
      dim: "流动性",
      name: "10Y 国债收益率（中债）",
      value: "1.769%",
      delta:
        "较前期约1.80%继续小幅下行，债市需求旺盛。中美利差（DGS10 4.59% vs 中债1.77%）扩大至282bp，资本流出压力略增。",
      signal: "green",
      updatedAt: "2026-05-08",
      source: "https://cn.investing.com/rates-bonds/china-10-year-bond-yield",
      sourceLabel: "Investing.com·中债10Y",
    },
    {
      dim: "汇率",
      name: "USD/CNY",
      value: "约 7.22",
      delta:
        "美元反弹（DXY 99.27），人民币小幅承压。峰会期间汇率相对平稳，央行维稳意图明确。",
      signal: "yellow",
      updatedAt: "2026-05-15",
      source: "https://www.chinamoney.com.cn",
      sourceLabel: "外汇交易中心",
    },
    {
      dim: "市场",
      name: "南向资金（日净买入）",
      value: "待更新",
      delta:
        "请查东方财富沪深港通数据更新本周南向资金净流入。",
      signal: "yellow",
      updatedAt: "2026-05-15",
      source: "https://data.eastmoney.com/hsgt/hsgtV2.html",
      sourceLabel: "东方财富·沪深港通",
    },
    {
      dim: "市场",
      name: "全A成交额",
      value: "待更新",
      delta:
        "请查东方财富更新本周全A成交额数据。",
      signal: "yellow",
      updatedAt: "2026-05-15",
      source: "https://data.eastmoney.com/zjlx/detail.html",
      sourceLabel: "东方财富·资金流向",
    },
    {
      dim: "市场",
      name: "融资融券余额",
      value: "待更新",
      delta:
        "请查东方财富更新本周两融余额数据。",
      signal: "yellow",
      updatedAt: "2026-05-15",
      source: "https://data.eastmoney.com/rzrq/total.html",
      sourceLabel: "东方财富·两融",
    },
    {
      dim: "增长",
      name: "工业增加值 YoY",
      value: "待核对",
      delta: "3月数据 4/17已发布 · 请查国家统计局官网",
      signal: "yellow",
      updatedAt: "2026-03",
      source: "https://www.stats.gov.cn",
      sourceLabel: "国家统计局",
    },
    {
      dim: "增长",
      name: "社零 YoY",
      value: "待核对",
      delta: "3月数据 4/17已发布 · 请查国家统计局官网",
      signal: "yellow",
      updatedAt: "2026-03",
      source: "https://www.stats.gov.cn",
      sourceLabel: "国家统计局",
    },
    {
      dim: "增长",
      name: "出口 YoY",
      value: "待核对",
      delta: "3月数据已发布（前值+21.8%）· 关税前抢出口效应",
      signal: "yellow",
      updatedAt: "2026-03",
      source: "http://www.customs.gov.cn",
      sourceLabel: "海关总署",
    },
    {
      dim: "增长",
      name: "地产开发投资 YoY",
      value: "待核对",
      delta: "Q1数据 4/17已发布（前值Q1 -11.1%）",
      signal: "red",
      updatedAt: "2026-Q1",
      source: "https://www.stats.gov.cn",
      sourceLabel: "国家统计局",
    },
    {
      dim: "流动性",
      name: "社融新增",
      value: "待核对",
      delta: "3月社融已发布（前值2月2.38万亿）· 信贷拐点关键观察",
      signal: "yellow",
      updatedAt: "2026-03",
      source: "https://www.pbc.gov.cn",
      sourceLabel: "央行",
    },
    {
      dim: "流动性",
      name: "贷款余额增速 YoY",
      value: "+6.0%",
      delta: "二十年新低（2月）· 信贷传导不畅 · 降准预期升温",
      signal: "red",
      updatedAt: "2026-02",
      source: "https://www.pbc.gov.cn",
      sourceLabel: "央行",
    },
  ],
  usKpis: [
    {
      dim: "增长",
      name: "非农就业",
      value: "+178K",
      delta: "↑（前值-133K，预期60K）· 失业率4.3% · 关税冲击尚未传导",
      signal: "green",
      updatedAt: "2026-03",
      source: "https://www.bls.gov",
      sourceLabel: "BLS",
    },
    {
      dim: "增长",
      name: "ISM制造业PMI",
      value: "52.7",
      delta: "↑0.3 · 连续3月扩张 · 4月数据或因关税+油价走弱",
      signal: "green",
      updatedAt: "2026-03",
      source: "https://www.ismworld.org",
      sourceLabel: "ISM",
    },
    {
      dim: "增长",
      name: "ISM服务业PMI",
      value: "54.0",
      delta: "连续21月扩张 · 新订单60.6 · 暂未受关税直接冲击",
      signal: "green",
      updatedAt: "2026-03",
      source: "https://www.ismworld.org",
      sourceLabel: "ISM",
    },
    {
      dim: "增长",
      name: "零售销售 MoM",
      value: "待核对",
      delta: "3月数据 ~4/16发布（前值+0.6%）",
      signal: "yellow",
      updatedAt: "2026-03",
      source: "https://www.census.gov",
      sourceLabel: "Census",
    },
    {
      dim: "通胀",
      name: "CPI YoY（4月）",
      value: "3.8%",
      delta: "↑↑ 超预期！（前值3.3%，预期3.7%）· 2023年5月以来最高 · 能源+3.8%（占月度涨幅40%以上）· 关税通胀传导确认 · 实际工资-0.5%",
      signal: "red",
      updatedAt: "2026-05-12",
      source: "https://www.bls.gov/news.release/cpi.nr0.htm",
      sourceLabel: "BLS·4月CPI",
    },
    {
      dim: "通胀",
      name: "核心CPI YoY（4月）",
      value: "2.8%",
      delta: "↑ 从3月2.6%升至2.8% · 服务业通胀顽固 · 核心环比+0.4%（翻倍）",
      signal: "red",
      updatedAt: "2026-05-12",
      source: "https://www.bls.gov/news.release/cpi.nr0.htm",
      sourceLabel: "BLS·核心CPI",
    },
    {
      dim: "通胀",
      name: "核心PCE（Q1折年）",
      value: "4.3%",
      delta: "Q1 2026年化折率 · Fed最关注指标 · 关税传导显著",
      signal: "red",
      updatedAt: "2026-Q1",
      source: "https://www.bea.gov",
      sourceLabel: "BEA",
    },
    {
      dim: "利率",
      name: "联邦基金利率",
      value: "3.50–3.75%",
      delta: "4/29维持不变 · 下次FOMC 6月 · CPI 3.8%后市场定价年内不降息",
      signal: "yellow",
      updatedAt: "2026-04-29",
      source: "https://www.federalreserve.gov",
      sourceLabel: "Fed",
    },
    {
      dim: "利率",
      name: "10Y Treasury DGS10",
      value: "4.59%",
      delta: "↑↑ 本周从4.41%飙升18bp至4.59%！CPI超预期+油价飙升双重推升。成长股估值承压。",
      signal: "red",
      updatedAt: "2026-05-15",
      source: "https://fred.stlouisfed.org/series/DGS10",
      sourceLabel: "FRED",
    },
    {
      dim: "利率",
      name: "10Y TIPS 实际利率",
      value: "~2.10%",
      delta: "↑ 名义利率上行带动实际利率走高 · 压制全球成长股估值",
      signal: "red",
      updatedAt: "2026-05-15",
      source: "https://fred.stlouisfed.org/series/DFII10",
      sourceLabel: "FRED",
    },
    {
      dim: "美元",
      name: "DXY 美元指数",
      value: "99.27",
      delta: "↑ 从97.84反弹至99.27（+1.5%），CPI超预期驱动美元走强。对新兴市场和黄金偏负面。",
      signal: "yellow",
      updatedAt: "2026-05-15",
      source: "https://finance.yahoo.com/quote/DX-Y.NYB/",
      sourceLabel: "ICE",
    },
    {
      dim: "风险偏好",
      name: "VIX",
      value: "18.43",
      delta: "↑ 从17.19升至18.43。CPI超预期+油价飙升推升波动率，尤其周五VIX盘中触19.27。",
      signal: "yellow",
      updatedAt: "2026-05-15",
      source: "https://fred.stlouisfed.org/series/VIXCLS",
      sourceLabel: "CBOE",
    },
    {
      dim: "信用",
      name: "HY信用利差",
      value: "~420bp",
      delta: "维持高位 · 关税衰退+油价通胀双重压力 · 信用市场仍谨慎",
      signal: "yellow",
      updatedAt: "2026-04-17",
      source: "https://fred.stlouisfed.org/series/BAMLH0A0HYM2",
      sourceLabel: "FRED",
    },
  ],
  framework: {
    growth: {
      title: "增长 Growth",
      metrics: ["官方PMI 50.3% + 财新52.2%（双重确认扩张）", "峰会：贸易投资委员会成立，但关税实质未减", "上证4,135（本周-1.1%）"],
      note: "增长基本面仍稳（PMI双双扩张），但特朗普-习近平峰会实质成果有限——「声势大雨点小」，关税145%未变。波音订单、大豆采购等属象征性让步。制造业面临油价成本上升+关税双重压力。",
    },
    inflation: {
      title: "通胀 Inflation",
      metrics: ["美国CPI 3.8%（超预期，确认关税通胀）", "中国PPI +2.8%（从+0.5%跳升，油价驱动）", "布伦特$109（伊朗局势再升温）"],
      note: "本周通胀是最大的宏观风险。美国CPI 3.8%确认关税→通胀传导路径；中国PPI +2.8%跳升受油价驱动；布伦特重回$109（霍尔木兹海峡局势紧张）。降息预期进一步推迟——市场定价年内可能不降息。",
    },
    liquidity: {
      title: "流动性 Liquidity",
      metrics: ["DGS10 4.59%（↑18bp，通胀驱动）", "DXY 99.27（美元反弹+1.5%）", "中国DR007 1.44%（宽松维持）"],
      note: "全球流动性本周边际收紧。DGS10飙升18bp至4.59%是核心变量——成长股折现率上升，估值承压。DXY反弹至99以上，对新兴市场资金流偏负面。但中国国内流动性仍宽松（DR007低位，10Y中债1.77%），A股受内部流动性支撑。",
    },
    risk: {
      title: "风险偏好 Risk",
      metrics: ["VIX 18.43（↑，波动率上升）", "SPX 7,408（周中创7,517纪录后回落）", "黄金$4,556（-3.7%，DXY反弹压制）", "布伦特$109（伊朗地缘风险）"],
      note: "风险偏好从上周的偏乐观转为偏谨慎。CPI超预期+油价飙升是双重打击。SPX周中创纪录7,517但周五大跌-1.1%。黄金回落但仍在$4,500+高位。峰会未能提供市场期待的关税缓解催化剂。",
    },
  },
  aShare: {
    indices: [
      { name: "上证综指", value: "4,135.4", change: "-1.1%", direction: "down" },
      { name: "深证成指", value: "15,220", change: "-2.2%", direction: "down" },
      { name: "创业板指", value: "3,680", change: "-3.1%", direction: "down" },
      { name: "沪深300", value: "4,810", change: "-1.3%", direction: "down" },
    ],
    sectorsTop: [
      { name: "上游材料/能源", note: "PPI +2.8%跳升+布伦特$109，上游利润预期改善" },
      { name: "黄金/贵金属", note: "金价虽回落至$4,556，但地缘不确定性持续支撑" },
      { name: "内需消费", note: "关税隔离+CPI温和（+1.2%），内需板块相对抗跌" },
    ],
    sectorsBottom: [
      { name: "出口依赖制造业", note: "峰会未缓解145%关税，出口链持续承压" },
      { name: "成长/科技", note: "DGS10飙升+全球流动性收紧，成长股估值承压" },
      { name: "航空/交通运输", note: "油价$109创年内新高，成本压力巨大" },
    ],
    flows: [
      {
        label: "南向净买入",
        valueText: "待更新（请查东财数据）",
        bar: 50,
      },
      {
        label: "融资融券余额",
        valueText: "待更新",
        bar: 60,
      },
      {
        label: "宽基ETF申赎",
        valueText: "待观察（国家队动态）",
        bar: 55,
      },
      {
        label: "全A成交",
        valueText: "待更新",
        bar: 60,
      },
    ],
  },
  usMarket: [
    { label: "联邦基金目标区间", value: "3.50%–3.75%（4/29维持不变，CPI 3.8%后市场定价年内不降息）" },
    {
      label: "CPI 同比（4月）",
      value: "3.8%（5/12发布，超预期！前值3.3%，预期3.7%）· 能源+3.8%是主要推手 · 核心CPI 2.8%",
    },
    { label: "核心 PCE 同比（Q1折年）", value: "4.3%（BEA: Q1 2026年化折率，关税传导显著）" },
    { label: "10Y 名义利率 DGS10", value: "4.59%（↑18bp！5/15；CPI+油价双重推升）" },
    { label: "10Y TIPS（实际利率）", value: "~2.10%（↑，名义利率上行驱动）" },
    { label: "标普500 SPX", value: "7,408（周中创纪录7,517后回落；本周持平；YTD约+8%）" },
    {
      label: "纳斯达克 IXIC / NDX",
      value: "26,225 / 29,125（NDX本周-0.4%，DGS10上行压制成长股）",
    },
    { label: "布伦特原油 Brent", value: "$109.3/桶（↑+7.9%！伊朗/霍尔木兹海峡紧张再度升温）" },
    { label: "黄金 XAU/USD", value: "$4,556/盎司（-3.7%，DXY反弹+美债利率上行压制）" },
    { label: "DXY 美元指数", value: "99.27（↑+1.5%，CPI超预期驱动美元反弹）" },
  ],
  usMarketAssets: [
    { name: "S&P 500", value: "7,408", wow: "持平", wowDir: "neutral", note: "周中创7,517纪录后回落" },
    { name: "Nasdaq / NDX", value: "26,225 / 29,125", wow: "-0.4%", wowDir: "down", note: "DGS10上行压制成长股" },
    { name: "Russell 2000", value: "~1,780", wow: "-1.5%", wowDir: "down", note: "小盘对利率更敏感" },
    { name: "黄金 XAU/USD", value: "$4,556", wow: "-3.7%", wowDir: "down", note: "DXY反弹+美债利率上行" },
    { name: "布伦特原油", value: "$109.3/桶", wow: "+7.9%", wowDir: "up", note: "伊朗/霍尔木兹紧张升温" },
  ],
  usContext: {
    styleNote: "价值>成长（DGS10飙升压制成长股估值）· 能源强势（布伦特$109）· 黄金回落",
    sectorNote: "能源+7.9%（油价驱动）· 公用事业+防御板块抗跌 · 科技/成长承压",
    narrative: [
      { title: "① 贸易战（主线）", text: "美国对华关税145% / 中国反制125%，格局未变。特朗普-习近平北京峰会（5/14-15）声势浩大但实质有限——波音订单、大豆采购属象征性让步，关税未降。市场反应平淡。" },
      { title: "② 美伊/油价（升温）", text: "布伦特重回$109（+7.9%），霍尔木兹海峡局势再度紧张。油价飙升是本周通胀预期上行的核心推手。若突破$115→通胀螺旋风险。" },
      { title: "③ 通胀回归", text: "4月CPI 3.8%超预期（前值3.3%），核心CPI 2.8%。DGS10飙升18bp至4.59%。市场定价年内不降息。" },
      { title: "④ 美联储两难", text: "通胀上行（CPI 3.8%）vs增长下行压力。下次FOMC 6月，降息路径高度不确定。" },
    ],
  },
  drivers: [
    { rank: 1, name: "油价/伊朗局势", detail: "布伦特$109（+7.9%）<br><strong>阈值：</strong>$115+→通胀螺旋 / <$95→压力缓解<br><strong>影响：</strong>通胀预期、PPI、美联储路径" },
    { rank: 2, name: "中美关税（峰会后续）", detail: "145%/125%未变，峰会实质有限<br><strong>阈值：</strong>实质降关税=反转催化<br><strong>影响：</strong>出口链、港股、全球供应链" },
    { rank: 3, name: "DGS10/美债利率", detail: "4.59%（本周+18bp）<br><strong>阈值：</strong>>4.70%=成长股大幅承压<br><strong>影响：</strong>全球成长股估值、黄金、美元" },
    { rank: 4, name: "美联储路径", detail: "CPI 3.8%后市场定价年内不降息<br><strong>阈值：</strong>6月FOMC措辞变化<br><strong>影响：</strong>全球利率锚与风险资产定价" },
    { rank: 5, name: "中国政策对冲", detail: "PPI +2.8%或限制降息空间<br><strong>阈值：</strong>降准落地=流动性信号<br><strong>影响：</strong>A股内需链核心变量" },
  ],
  scenarios: [
    {
      name: "基准",
      probability: "45%",
      text: "通胀高位→降息推迟到2027年；峰会后关税战维持现状（145%不变）；油价$100-110震荡；A股在增长韧性和外部压力间横盘，上证4,000-4,200区间。",
    },
    {
      name: "乐观",
      probability: "25%",
      text: "峰会后续出现实质关税减免（如部分商品降至60%）；伊朗局势缓和，布伦特回落至$90-95；降息预期重现；出口链和港股强势反弹，上证冲击4,400+。",
    },
    {
      name: "悲观",
      probability: "30%",
      text: "油价突破$120（霍尔木兹海峡进一步封锁）；CPI持续走高（>4%）；美联储被迫偏鹰甚至加息讨论；DGS10突破5%；全球风险资产大幅回调，A股受外溢效应下探3,800。",
    },
  ],
  watchlist: [
    {
      title: "⚠️ 油价走向（布伦特 $109，伊朗/霍尔木兹关键）",
      condition: "是否突破$115+（霍尔木兹海峡完全封锁）或回落至$100以下",
      action: "突破$115→通胀螺旋，全球衰退风险升级；回落$100以下→通胀压力缓解，降息路径重现",
      source: "yfinance BZ=F / 财经终端",
    },
    {
      title: "⚠️ 特朗普-习近平峰会后续落实",
      condition: "峰会承诺是否转化为实质关税减免",
      action: "实质降关税→出口链大幅反弹，市场重定价；仅象征性落实→市场失望，出口链继续承压",
      source: "商务部/USTR/新华社",
    },
    {
      title: "DGS10 走势（当前4.59%）",
      condition: "是否突破4.70%或回落至4.40%以下",
      action: "突破4.70%→成长股估值大幅承压，科技板块回调；回落4.40%→估值修复，成长股反弹",
      source: "FRED: DGS10 / yfinance ^TNX",
    },
    {
      title: "5月下旬非农/就业数据",
      condition: "失业率是否从4.3%进一步上升",
      action: "失业率升至4.5%+→衰退担忧升温，但可能重启降息讨论；维持4.3%→经济韧性确认",
      source: "BLS（6月第一个周五）",
    },
    {
      title: "央行政策对冲（降准/降息）",
      condition: "PPI +2.8%是否改变央行宽松节奏",
      action: "PPI上行限制降息空间，但经济下行压力仍大，降准更可能先行",
      source: "人民银行",
    },
    {
      title: "VIX 走势（当前18.43）",
      condition: "VIX > 22（油价+通胀双重压力下可能触发）",
      action: "风险资产快速回调信号；关注A股资金流出",
      source: "yfinance ^VIX",
    },
  ],
};
