/**
 * A股宏观看板 — 数据字典（Glossary / Data Dictionary）
 * =====================================================
 * 每个指标的完整定义、口径、频率、来源、信号规则、注意事项。
 */
window.GLOSSARY = [
  // ===================================================================
  //  中国 · 增长
  // ===================================================================
  {
    category: "中国 · 增长",
    id: "cn_pmi_nbs",
    name: "NBS 官方制造业 PMI",
    nameEn: "NBS Manufacturing PMI",
    definition: "中国国家统计局联合中国物流与采购联合会编制的采购经理指数。对约 3000 家制造业企业进行月度调查，涵盖生产、新订单、原材料库存、从业人员、供应商配送时间五个分项，加权合成综合 PMI。",
    unit: "%（扩散指数）",
    range: "0–100；50 为荣枯分界线",
    frequency: "月度，每月最后一天或次月第一个工作日发布",
    publishTime: "通常 09:00 (CST)",
    source: "国家统计局",
    sourceUrl: "https://www.stats.gov.cn/sj/zxfbhjd/",
    methodology: "扩散指数法：各分项先算扩散指数（回答「上升」占比 + 回答「持平」占比 × 0.5），再加权合成。权重：新订单30%、生产25%、从业人员20%、供应商配送时间15%、原材料库存10%。",
    seasonalAdj: "经季节调整",
    revisionRisk: "低，一般不修订",
    signalRule: ">51 → 绿（扩张）| 50–51 → 黄（临界）| <50 → 红（收缩）。连续方向比单月绝对值更重要。",
    caveats: "NBS PMI 样本偏大型国企，与财新 PMI（偏中小民企）可能出现背离。1-2月受春节影响较大。",
    relatedIndicators: ["财新制造业PMI", "工业增加值", "新订单指数"],
    fredCode: null,
    akshareFunc: "macro_china_pmi()",
  },
  {
    category: "中国 · 增长",
    id: "cn_pmi_caixin",
    name: "财新制造业 PMI",
    nameEn: "Caixin Manufacturing PMI",
    definition: "由财新传媒与标普全球（S&P Global / Markit）合作编制的中国制造业采购经理指数。基于约 650 家中小型私营制造企业的月度调查。",
    unit: "%（扩散指数）",
    range: "0–100；50 为荣枯分界线",
    frequency: "月度，次月第一个工作日发布（通常比NBS晚1天）",
    publishTime: "09:45 (CST)",
    source: "财新 / S&P Global",
    sourceUrl: "https://www.caixinglobal.com/caixin-manufacturing-pmi/",
    methodology: "与NBS方法论类似（扩散指数），但样本不同：偏中小型民营企业，地域分布更侧重沿海出口型经济。",
    seasonalAdj: "经季节调整",
    revisionRisk: "低",
    signalRule: "同NBS PMI规则。当NBS与财新出现背离时，需关注大型国企 vs 中小民企的分化。",
    caveats: "样本量较NBS小（~650 vs ~3000），波动可能更大。",
    relatedIndicators: ["NBS官方PMI", "出口新订单", "就业指数"],
    fredCode: null,
    akshareFunc: null,
  },
  {
    category: "中国 · 增长",
    id: "cn_ip",
    name: "工业增加值 YoY",
    nameEn: "Industrial Value Added (YoY)",
    definition: "规模以上工业企业（年主营业务收入≥2000万元）的工业增加值同比增速。反映工业生产活动的实际增长。",
    unit: "% YoY（同比）",
    range: "通常 3%–8%",
    frequency: "月度（1-2月合并发布），每月15日前后",
    publishTime: "10:00 (CST)",
    source: "国家统计局",
    sourceUrl: "https://www.stats.gov.cn/english/PressRelease/",
    methodology: "以不变价格计算。增加值 = 总产出 - 中间投入。「规模以上」门槛为年收入≥2000万元。",
    seasonalAdj: "统计局发布经季调环比，但市场更关注同比",
    revisionRisk: "中等，年度经济普查后可能修订",
    signalRule: ">6% → 绿 | 4%–6% → 黄 | <4% → 红",
    caveats: "1-2月合并发布（避免春节扰动）。高技术制造业和装备制造业增速通常更有参考价值。",
    relatedIndicators: ["制造业PMI", "用电量", "PPI"],
    fredCode: null,
    akshareFunc: "macro_china_industrial_production()",
  },
  {
    category: "中国 · 增长",
    id: "cn_retail",
    name: "社会消费品零售总额 YoY",
    nameEn: "Retail Sales of Consumer Goods (YoY)",
    definition: "社会消费品零售总额是批发和零售业、住宿和餐饮业以及其他行业直接售给城乡居民和社会集团的消费品零售额。反映消费端需求强度。",
    unit: "% YoY（同比，名义值）",
    range: "通常 2%–10%",
    frequency: "月度（1-2月合并），每月15日前后",
    publishTime: "10:00 (CST)",
    source: "国家统计局",
    sourceUrl: "https://www.stats.gov.cn/english/PressRelease/",
    methodology: "名义值同比。包含实物商品和餐饮收入。不扣除价格因素（需结合CPI看实际增速）。",
    seasonalAdj: "无官方季调（1-2月合并处理春节）",
    revisionRisk: "低",
    signalRule: ">4% → 绿 | 2%–4% → 黄 | <2% → 红",
    caveats: "名义值受CPI影响。春节、国庆等节假日月份季节性明显。网上零售增速通常远高于总体。",
    relatedIndicators: ["CPI", "消费者信心指数", "网上零售额"],
    fredCode: null,
    akshareFunc: null,
  },
  {
    category: "中国 · 增长",
    id: "cn_exports",
    name: "出口同比（美元计）",
    nameEn: "Exports YoY (USD)",
    definition: "中国海关总署公布的月度出口总额同比增速（以美元计价）。反映外需强弱和中国制造业国际竞争力。",
    unit: "% YoY（美元计）",
    range: "波动大，-20% ~ +30%",
    frequency: "月度（1-2月合并），每月7-10日前后",
    publishTime: "通常上午",
    source: "海关总署",
    sourceUrl: "http://www.customs.gov.cn/",
    methodology: "按报关日期统计，以美元计价。1-2月合并公布避免春节扰动。人民币计价数据同步发布。",
    seasonalAdj: "无官方季调，1-2月合并处理",
    revisionRisk: "低",
    signalRule: ">10% → 绿 | 0%–10% → 黄 | <0% → 红",
    caveats: "受基数效应、汇率波动、抢出口（关税预期下提前发货）影响大。对美出口受贸易战影响需单独跟踪。",
    relatedIndicators: ["PMI新出口订单", "人民币汇率", "全球PMI"],
    fredCode: null,
    akshareFunc: null,
  },
  {
    category: "中国 · 增长",
    id: "cn_property",
    name: "房地产开发投资 YoY",
    nameEn: "Real Estate Development Investment (YoY)",
    definition: "房地产开发企业在土地购置、房屋施工、安装、设备购置等方面的投资额同比增速。反映地产行业的投资活动强度。",
    unit: "% YoY（累计同比）",
    range: "近年 -20% ~ +15%",
    frequency: "月度（1-2月合并），每月15日前后",
    publishTime: "10:00 (CST)",
    source: "国家统计局",
    sourceUrl: "https://www.stats.gov.cn/english/PressRelease/",
    methodology: "包括住宅和商业不动产。统计口径为累计同比（1-N月累计值 vs 上年同期）。",
    seasonalAdj: "无",
    revisionRisk: "中等",
    signalRule: "降幅收窄 → 黄（改善）| 转正 → 绿 | 降幅扩大 → 红",
    caveats: "当前处于下行周期，关注降幅收窄/扩大的边际变化比绝对水平更重要。需结合销售面积、新开工、到位资金等分项综合判断。",
    relatedIndicators: ["新建商品房销售面积", "房价指数（70城）", "房企到位资金"],
    fredCode: null,
    akshareFunc: null,
  },
  // ===================================================================
  //  中国 · 通胀
  // ===================================================================
  {
    category: "中国 · 通胀",
    id: "cn_cpi",
    name: "CPI 同比",
    nameEn: "Consumer Price Index (YoY)",
    definition: "居民消费价格指数同比涨幅。衡量一篮子消费品和服务价格相对上年同期的变动。是中国最主要的通胀指标。",
    unit: "% YoY",
    range: "政策目标：约 +3%；近年实际：-1% ~ +3%",
    frequency: "月度，次月9-12日发布",
    publishTime: "09:30 (CST)",
    source: "国家统计局",
    sourceUrl: "https://www.stats.gov.cn/sj/zxfbhjd/",
    methodology: "采用拉氏公式，对8大类262个基本分类约500个调查规格品价格加权计算。权重基于居民消费支出结构，每5年换基一次（2026年换基至2025年=100）。",
    seasonalAdj: "统计局同时发布环比和同比",
    revisionRisk: "极低",
    signalRule: "0.5%–2.5% → 绿（温和通胀）| <0.5% 或 2.5%–3% → 黄 | <0% 或 >3% → 红",
    caveats: "食品（尤其猪肉）权重较大，波动可能掩盖趋势。核心CPI（扣除食品和能源）更能反映需求拉动的通胀。2026年1月起已换基。",
    relatedIndicators: ["核心CPI", "PPI", "食品价格"],
    fredCode: null,
    akshareFunc: "macro_china_cpi_monthly()",
  },
  {
    category: "中国 · 通胀",
    id: "cn_core_cpi",
    name: "核心 CPI 同比",
    nameEn: "Core CPI (YoY)",
    definition: "扣除食品和能源价格后的CPI同比涨幅。剔除波动性最大的两个分项，更好反映需求端的价格趋势。",
    unit: "% YoY",
    range: "通常 0% ~ 2%",
    frequency: "月度（与CPI同步发布）",
    publishTime: "09:30 (CST)",
    source: "国家统计局",
    sourceUrl: "https://www.stats.gov.cn/sj/zxfbhjd/",
    methodology: "CPI总指数中扣除食品和能源分项后的加权指数。",
    seasonalAdj: "无",
    revisionRisk: "极低",
    signalRule: "与CPI信号配合使用。核心CPI上行+CPI上行 → 需求驱动型通胀；核心CPI平稳+CPI上行 → 供给冲击（食品/能源）。",
    caveats: "中国核心CPI长期处于低位，持续低于1%可能反映内需不足。",
    relatedIndicators: ["CPI", "服务业CPI", "居民收入"],
    fredCode: null,
    akshareFunc: null,
  },
  {
    category: "中国 · 通胀",
    id: "cn_ppi",
    name: "PPI 同比",
    nameEn: "Producer Price Index (YoY)",
    definition: "工业生产者出厂价格指数同比涨幅。衡量工业企业出厂产品价格的变动，是观察上游/中游价格趋势和工业利润的核心指标。",
    unit: "% YoY",
    range: "-6% ~ +10%",
    frequency: "月度，次月9-12日发布（与CPI同日）",
    publishTime: "09:30 (CST)",
    source: "国家统计局",
    sourceUrl: "https://www.stats.gov.cn/sj/zxfbhjd/",
    methodology: "覆盖采掘、原材料、加工和生活资料四大类约1600种工业产品的出厂价格。采用加权算术平均。",
    seasonalAdj: "无官方季调",
    revisionRisk: "低",
    signalRule: ">0% → 绿（再通胀）| -2%~0% → 黄 | <-2% → 红（通缩）",
    caveats: "PPI转正可能是油价等外生因素驱动（需区分成本推动 vs 需求拉动）。PPI与CPI的「剪刀差」反映利润在上下游间的分配。",
    relatedIndicators: ["CPI", "大宗商品价格", "工业企业利润"],
    fredCode: null,
    akshareFunc: "macro_china_ppi_monthly()",
  },
  // ===================================================================
  //  中国 · 流动性/信用
  // ===================================================================
  {
    category: "中国 · 流动性",
    id: "cn_tsf",
    name: "社会融资规模增量",
    nameEn: "Total Social Financing (TSF) Flow",
    definition: "实体经济从金融体系获得的资金总额（增量），包括人民币贷款、外币贷款、委托贷款、信托贷款、未贴现银行承兑汇票、企业债券、政府债券、非金融企业境内股票融资等。是衡量整体信用扩张的核心指标。",
    unit: "亿元人民币（月增量）",
    range: "季节性波动大，1月通常最高（开门红）",
    frequency: "月度，次月10-15日发布",
    publishTime: "不固定，通常下午",
    source: "中国人民银行",
    sourceUrl: "https://www.pbc.gov.cn/",
    methodology: "加总各融资渠道的月增量。口径历年有扩展（如2018年纳入地方政府专项债）。存量增速 = TSF存量同比。",
    seasonalAdj: "无（1月「开门红」效应显著）",
    revisionRisk: "低，但口径调整频繁",
    signalRule: "超预期>20% → 绿 | 符合预期±10% → 黄 | 不及预期>20% → 红",
    caveats: "1月因银行抢投放，数据季节性极强。政府债券发行节奏受财政政策影响大。需同时看人民币贷款结构（中长期vs短期）。",
    relatedIndicators: ["新增人民币贷款", "M2增速", "信贷脉冲"],
    fredCode: null,
    akshareFunc: "macro_china_shrzgm()",
  },
  {
    category: "中国 · 流动性",
    id: "cn_loan_growth",
    name: "贷款余额增速 YoY",
    nameEn: "Outstanding Loan Growth (YoY)",
    definition: "金融机构人民币各项贷款余额的同比增长率。反映银行信贷投放的中长期趋势。",
    unit: "% YoY",
    range: "通常 6%–14%",
    frequency: "月度",
    publishTime: "与社融同步",
    source: "中国人民银行",
    sourceUrl: "https://www.pbc.gov.cn/",
    methodology: "人民币贷款余额同比变动率。",
    seasonalAdj: "无",
    revisionRisk: "低",
    signalRule: ">7% → 绿 | 6%–7% → 黄 | <6% → 红",
    caveats: "近年持续下行，6%为二十年低位，反映信贷需求疲弱和去杠杆效应。",
    relatedIndicators: ["社融", "M2增速", "企业中长期贷款"],
    fredCode: null,
    akshareFunc: null,
  },
  {
    category: "中国 · 流动性",
    id: "cn_m2_m1",
    name: "M1/M2 增速与M2-M1缺口",
    nameEn: "M1/M2 Growth & Gap",
    definition: "M2 = 广义货币供应量（现金+活期存款+定期存款+储蓄存款等）；M1 = 狭义货币供应量（现金+企业活期存款）。M2-M1缺口反映资金活化程度——缺口收窄意味着企业活期存款增加（资金从定期转活期，经济活跃度上升）。",
    unit: "% YoY",
    range: "M2通常 6%–12%；M1波动更大",
    frequency: "月度",
    publishTime: "与社融同步",
    source: "中国人民银行",
    sourceUrl: "https://www.pbc.gov.cn/",
    methodology: "央行按月统计各层次货币供应量存量，计算同比增速。2025年起M1口径调整，纳入个人活期存款和非银支付机构客户备付金。",
    seasonalAdj: "无",
    revisionRisk: "低（但口径调整后需重新对比）",
    signalRule: "M2-M1缺口收窄 → 积极信号（资金活化）| 缺口扩大 → 资金空转（利空）",
    caveats: "2025年M1口径重大调整（纳入个人活期存款），与历史数据不可直接对比。",
    relatedIndicators: ["社融", "DR007", "贷款增速"],
    fredCode: "MYAGM2CNM189N (M2 on FRED)",
    akshareFunc: "macro_china_money_supply()",
  },
  {
    category: "中国 · 流动性",
    id: "cn_dr007",
    name: "DR007",
    nameEn: "Depository Institutions 7-Day Repo Rate",
    definition: "银行间市场存款类金融机构以利率债为质押的7天期回购加权平均利率。是中国银行间市场最核心的短期利率指标，被视为央行流动性管理的「锚」。",
    unit: "%",
    range: "通常在7天逆回购利率（政策利率）附近 ±20bp",
    frequency: "日度",
    publishTime: "每日收盘后",
    source: "中国外汇交易中心（CFETS）",
    sourceUrl: "https://www.chinamoney.com.cn/english/bmkfrr/",
    methodology: "以国债、央票、政策性金融债为质押品，存款类机构之间的7天回购交易加权平均利率。与R007（全机构口径）不同，DR007仅限存款类机构，更能反映银行体系流动性。",
    seasonalAdj: "无（月末、季末、年末有明显季节性上升）",
    revisionRisk: "无",
    signalRule: "与7天逆回购利率持平 → 绿 | 高于政策利率20bp+ → 黄 | 持续显著偏离 → 红",
    caveats: "月末、季末因MPA考核等因素波动加大。跨节假日期间资金价格也会上行。",
    relatedIndicators: ["7天逆回购利率", "Shibor", "R007"],
    fredCode: null,
    akshareFunc: null,
  },
  {
    category: "中国 · 流动性",
    id: "cn_10y_yield",
    name: "中国10年期国债收益率",
    nameEn: "China 10Y Government Bond Yield",
    definition: "10年期国债到期收益率（中债估值）。是中国无风险利率的基准，影响一切资产定价。",
    unit: "%",
    range: "近年 1.6%–3.2%",
    frequency: "日度",
    publishTime: "日间连续",
    source: "中债估值（ChinaBond）/ TradingEconomics",
    sourceUrl: "https://yield.chinabond.com.cn/",
    methodology: "中央国债登记结算有限责任公司（中债）基于市场交易和报价数据编制的到期收益率曲线。",
    seasonalAdj: "无",
    revisionRisk: "无",
    signalRule: "<1.8% → 绿（宽松）| 1.8%–2.2% → 黄 | >2.5% → 红 | 急跌可能反映避险而非宽松",
    caveats: "中美10Y利差倒挂（中国<美国）是常态。利率快速下行有时反映经济悲观预期而非单纯利好。",
    relatedIndicators: ["DR007", "美国10Y", "中美利差", "国债期货"],
    fredCode: null,
    akshareFunc: "bond_china_yield()",
  },
  // ===================================================================
  //  中国 · 汇率
  // ===================================================================
  {
    category: "中国 · 汇率",
    id: "usd_cny",
    name: "USD/CNY 即期汇率",
    nameEn: "USD/CNY Spot Rate",
    definition: "美元兑人民币即期汇率。数值下降代表人民币升值。是A股外资流向、进出口企业盈利、跨境资金流动的核心变量。",
    unit: "CNY per 1 USD",
    range: "近年 6.3–7.35",
    frequency: "日度（交易日）",
    publishTime: "每日09:15公布中间价，盘中连续交易",
    source: "中国外汇交易中心（CFETS）",
    sourceUrl: "https://www.chinamoney.com.cn/",
    methodology: "在岸即期汇率（CNY），区别于离岸汇率（CNH）。中间价由做市商报价经逆周期因子等调节后形成。",
    seasonalAdj: "无",
    revisionRisk: "无",
    signalRule: "<6.85 → 绿（升值利好A股）| 6.85–7.10 → 黄 | >7.20 → 红",
    caveats: "急速升值可能压制出口竞争力。需同时关注CNH（离岸）与CNY（在岸）价差。",
    relatedIndicators: ["DXY美元指数", "CFETS人民币指数", "北向资金"],
    fredCode: null,
    akshareFunc: "fx_spot_quote()",
  },
  {
    category: "中国 · 汇率",
    id: "cfets_index",
    name: "CFETS 人民币汇率指数",
    nameEn: "CFETS RMB Index",
    definition: "中国外汇交易中心编制的人民币对一篮子货币的加权汇率指数。以2014年末为基期100。反映人民币的整体有效汇率，比单一的USD/CNY更全面。",
    unit: "指数（基期=100）",
    range: "近年 95–105",
    frequency: "周度（每周五公布）",
    publishTime: "周五",
    source: "CFETS",
    sourceUrl: "https://www.chinamoney.com.cn/chinese/bkrmbidx/",
    methodology: "参考BIS货币篮子和SDR货币篮子，以贸易权重加权。2026年1月1日起美元权重从18.903%降至18.307%。",
    seasonalAdj: "无",
    revisionRisk: "低（但每年调整篮子权重）",
    signalRule: ">100 → 人民币相对篮子偏强 | <98 → 偏弱",
    caveats: "篮子权重每年调整，纵向对比需注意。",
    relatedIndicators: ["USD/CNY", "DXY"],
    fredCode: null,
    akshareFunc: null,
  },
  // ===================================================================
  //  中国 · 风险偏好/市场
  // ===================================================================
  {
    category: "中国 · 市场",
    id: "cn_turnover",
    name: "全A成交额",
    nameEn: "A-Share Total Turnover",
    definition: "沪深两市（含北交所）全部A股的每日总成交金额。反映市场活跃度和参与意愿。是判断市场情绪的最直观指标之一。",
    unit: "万亿元人民币/日",
    range: "低迷 <0.8万亿 | 正常 1–2万亿 | 活跃 2–3万亿 | 过热 >3万亿",
    frequency: "日度",
    publishTime: "每日15:00收盘后",
    source: "上交所 / 深交所 / 东方财富",
    sourceUrl: "https://data.eastmoney.com/",
    methodology: "沪市成交额 + 深市成交额（含北交所）。单边计算。",
    seasonalAdj: "无",
    revisionRisk: "无",
    signalRule: ">2.5万亿 → 绿（活跃）| 1.5–2.5万亿 → 黄 | <1.5万亿 → 红 | 连续>3万亿也需警惕过热",
    caveats: "建议用120日滚动分位数判断相对水平。缩量不一定跌、放量不一定涨，需结合价格方向。",
    relatedIndicators: ["换手率", "两融余额", "新开户数"],
    fredCode: null,
    akshareFunc: null,
  },
  {
    category: "中国 · 市场",
    id: "cn_margin",
    name: "两融余额（融资融券）",
    nameEn: "Margin Trading Balance",
    definition: "融资余额（投资者从券商借钱买股票的未偿还金额）+ 融券余额（借股票卖出的未偿还金额）。反映市场杠杆水平和方向性信心。融资余额远大于融券余额（通常占比>99%）。",
    unit: "亿元人民币",
    range: "低迷 <1.5万亿 | 正常 1.5–2.2万亿 | 活跃 2.2–2.8万亿 | 高位 >2.8万亿",
    frequency: "日度（T+1）",
    publishTime: "次日早间",
    source: "上交所/深交所 / 东方财富 / 同花顺",
    sourceUrl: "https://data.eastmoney.com/rzrq/",
    methodology: "沪市融资融券余额 + 深市融资融券余额。2026年1月监管将最低保证金比例提高至100%。",
    seasonalAdj: "无",
    revisionRisk: "无",
    signalRule: ">2.6万亿 → 绿（信心高）| 2.2–2.6万亿 → 黄 | <2.0万亿 → 红 | 快速飙升也是风险信号",
    caveats: "2026年1月起保证金比例100%的新规限制了杠杆。融资余额快速上升可能预示过热。",
    relatedIndicators: ["全A成交额", "上证综指", "融资买入额"],
    fredCode: null,
    akshareFunc: "stock_margin_sse()",
  },
  {
    category: "中国 · 市场",
    id: "cn_northbound",
    name: "北向资金（沪深港通）",
    nameEn: "Northbound Capital Flow (Stock Connect)",
    definition: "通过沪港通和深港通从香港流入A股的资金净额。北向资金被市场视为「聪明钱」（Smart Money），其流向常被作为外资对A股信心的代理指标。",
    unit: "亿元人民币/日",
    range: "日度波动大，-100亿~+200亿",
    frequency: "日度",
    publishTime: "每日盘中实时更新，收盘后确认",
    source: "港交所 / 东方财富",
    sourceUrl: "https://data.eastmoney.com/hsgt/",
    methodology: "沪股通净买入额 + 深股通净买入额。每日额度上限各520亿元（2023年3月起）。注意：2024年7月后不再披露实时数据，仅交易所事后汇总。",
    seasonalAdj: "无",
    revisionRisk: "低",
    signalRule: "周净流入>100亿 → 绿 | ±100亿 → 黄 | 周净流出>200亿 → 红",
    caveats: "2024年7月起实时数据不再披露，需T+1获取。北向资金中包含对冲基金和量化资金，不全是「长线价值投资」。",
    relatedIndicators: ["USD/CNY", "MSCI中国", "AH溢价指数"],
    fredCode: null,
    akshareFunc: "stock_hsgt_north_net_flow_in_em()",
  },
  // ===================================================================
  //  美国 · 增长
  // ===================================================================
  {
    category: "美国 · 增长",
    id: "us_nfp",
    name: "非农就业人数变化",
    nameEn: "Nonfarm Payrolls (Change)",
    definition: "美国劳工统计局（BLS）每月公布的非农业部门就业人数月度变化量。是美国最重要的经济指标之一，直接影响Fed政策预期。",
    unit: "千人（月度变化）",
    range: "正常 +100K~+300K | 强劲 >300K | 疲弱 <100K | 负值=衰退信号",
    frequency: "月度，每月第一个周五发布",
    publishTime: "08:30 (ET) / 20:30 (CST)",
    source: "BLS (Bureau of Labor Statistics)",
    sourceUrl: "https://www.bls.gov/news.release/empsit.nr0.htm",
    methodology: "基于约14.4万家企业/政府机构的调查（Establishment Survey）。不含农业、私人家庭雇员、非营利组织等。会经历两次修订。",
    seasonalAdj: "经季节调整",
    revisionRisk: "高（前两个月数据会修订，修订幅度有时超过10万）",
    signalRule: ">200K → 绿 | 100K–200K → 黄 | <100K → 红",
    caveats: "修订幅度可能很大。罢工（如2026年2月医疗罢工）会造成非经济因素的波动。需同时看失业率、劳动参与率、平均时薪。",
    relatedIndicators: ["失业率", "ADP私营就业", "初请失业金", "平均时薪"],
    fredCode: "PAYEMS",
    akshareFunc: null,
  },
  {
    category: "美国 · 增长",
    id: "us_ism_mfg",
    name: "ISM 制造业 PMI",
    nameEn: "ISM Manufacturing PMI",
    definition: "美国供应管理协会（ISM）编制的制造业采购经理指数。基于约300家制造业企业调查，是美国制造业景气度的标杆指标。",
    unit: "%（扩散指数）",
    range: "0–100；50 为荣枯线",
    frequency: "月度，每月第一个工作日",
    publishTime: "10:00 (ET) / 22:00 (CST)",
    source: "ISM (Institute for Supply Management)",
    sourceUrl: "https://www.ismworld.org/",
    methodology: "与中国PMI类似的扩散指数法。5个等权分项：新订单、生产、就业、供应商交付、库存。",
    seasonalAdj: "经季节调整",
    revisionRisk: "极低",
    signalRule: ">52 → 绿 | 50–52 → 黄 | <50 → 红",
    caveats: "制造业仅占美国GDP约11%，服务业PMI（ISM-NMI）同样重要。",
    relatedIndicators: ["ISM服务业PMI", "工业产出", "Markit PMI"],
    fredCode: "NAPM",
    akshareFunc: null,
  },
  // ===================================================================
  //  美国 · 通胀
  // ===================================================================
  {
    category: "美国 · 通胀",
    id: "us_cpi",
    name: "美国 CPI 同比",
    nameEn: "US CPI (YoY)",
    definition: "美国消费者价格指数同比涨幅。衡量城市消费者购买一篮子商品和服务的价格变动。是市场关注度最高的通胀指标。",
    unit: "% YoY",
    range: "Fed目标 2%；近年 2%–9%",
    frequency: "月度，次月10-13日发布",
    publishTime: "08:30 (ET) / 20:30 (CST)",
    source: "BLS",
    sourceUrl: "https://www.bls.gov/cpi/",
    methodology: "约80,000种商品和服务价格，覆盖约93%的美国城市人口（CPI-U）。基于消费者支出调查确定权重。",
    seasonalAdj: "发布季调和未季调两个版本",
    revisionRisk: "低（年度权重调整会影响后续月份）",
    signalRule: "<2.5% → 绿 | 2.5%–3% → 黄 | >3% → 红",
    caveats: "Fed实际关注的通胀指标是核心PCE而非CPI，但CPI因先发布而对市场影响更大。住房（Shelter）权重约36%，滞后性强。",
    relatedIndicators: ["核心CPI", "核心PCE", "PPI", "通胀预期"],
    fredCode: "CPIAUCSL",
    akshareFunc: null,
  },
  {
    category: "美国 · 通胀",
    id: "us_core_pce",
    name: "核心 PCE 同比",
    nameEn: "Core PCE Price Index (YoY)",
    definition: "扣除食品和能源后的个人消费支出价格指数同比涨幅。这是美联储最看重的通胀指标，Fed的2%通胀目标即以此衡量。",
    unit: "% YoY",
    range: "Fed目标 2%",
    frequency: "月度，次月末发布",
    publishTime: "08:30 (ET)",
    source: "BEA (Bureau of Economic Analysis)",
    sourceUrl: "https://www.bea.gov/data/personal-consumption-expenditures-price-index",
    methodology: "基于GDP核算中的消费支出数据，权重动态调整（Fisher链式指数）。与CPI相比，PCE权重更灵活、覆盖范围更广（含雇主代付的医疗保险等）。",
    seasonalAdj: "经季节调整",
    revisionRisk: "中等（随GDP修订而调整）",
    signalRule: "<2.2% → 绿 | 2.2%–2.8% → 黄 | >2.8% → 红",
    caveats: "发布时间晚于CPI约2周，但Fed更重视PCE。核心PCE通常低于核心CPI约0.3ppt。",
    relatedIndicators: ["美国CPI", "个人收入", "消费支出"],
    fredCode: "PCEPILFE",
    akshareFunc: null,
  },
  // ===================================================================
  //  美国 · 利率
  // ===================================================================
  {
    category: "美国 · 利率",
    id: "us_fed_funds",
    name: "联邦基金利率",
    nameEn: "Federal Funds Rate",
    definition: "美国银行间隔夜拆借利率的目标区间，由FOMC设定。是美国最核心的政策利率，影响全球资产定价。",
    unit: "%（目标区间，如 3.50%–3.75%）",
    range: "0%–5.5%（历史区间）",
    frequency: "FOMC会议后宣布（约每6周一次，每年8次）",
    publishTime: "14:00 (ET) / 02:00 (CST次日)",
    source: "Federal Reserve",
    sourceUrl: "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm",
    methodology: "FOMC投票决定。有效联邦基金利率（EFFR）是实际市场交易的加权平均。CME FedWatch工具可追踪市场对未来利率的概率定价。",
    seasonalAdj: "不适用",
    revisionRisk: "无",
    signalRule: "降息信号 → 绿 | 维持不变 → 黄 | 加息信号 → 红",
    caveats: "市场定价（期货隐含）常与Fed点阵图不一致。FOMC纪要（会后3周发布）和主席讲话同样重要。",
    relatedIndicators: ["CME FedWatch", "美国10Y", "美元指数"],
    fredCode: "DFF",
    akshareFunc: null,
  },
  {
    category: "美国 · 利率",
    id: "us_10y",
    name: "美国10年期国债收益率",
    nameEn: "US 10-Year Treasury Yield",
    definition: "美国10年期国债到期收益率。全球最重要的无风险利率基准，是一切资产估值的「锚」——影响房贷利率、企业融资成本、股票贴现率等。",
    unit: "%",
    range: "近年 1.5%–5.0%",
    frequency: "日度（连续交易）",
    publishTime: "连续",
    source: "U.S. Treasury / FRED",
    sourceUrl: "https://fred.stlouisfed.org/series/DGS10",
    methodology: "基于活跃交易的on-the-run国债的市场收益率。FRED取每日收盘观测值。",
    seasonalAdj: "无",
    revisionRisk: "无",
    signalRule: "<3.5% → 绿 | 3.5%–4.5% → 黄 | >4.5% → 红",
    caveats: "10Y = 实际利率（TIPS）+ 通胀预期（Breakeven）。上行可能是增长预期改善（利好）也可能是通胀失控（利空），需拆解。10Y-2Y利差反映曲线形态。",
    relatedIndicators: ["2Y收益率", "10Y TIPS", "Fed利率", "收益率曲线"],
    fredCode: "DGS10",
    akshareFunc: null,
  },
  {
    category: "美国 · 利率",
    id: "us_tips_10y",
    name: "10年期 TIPS 实际利率",
    nameEn: "10-Year TIPS Yield (Real Rate)",
    definition: "通胀保值国债（TIPS）的到期收益率。代表市场对未来10年「扣除通胀后」的实际回报要求。是美股（尤其成长股/科技股）估值的核心驱动变量。",
    unit: "%",
    range: "近年 -1% ~ +2.5%",
    frequency: "日度",
    publishTime: "连续",
    source: "FRED",
    sourceUrl: "https://fred.stlouisfed.org/series/DFII10",
    methodology: "10Y TIPS的市场到期收益率。名义10Y - TIPS 10Y = 10Y盈亏平衡通胀率（Breakeven）。",
    seasonalAdj: "无",
    revisionRisk: "无",
    signalRule: "<1.5% → 绿（宽松）| 1.5%–2.0% → 黄 | >2.0% → 红（restrictive）",
    caveats: "实际利率上升对成长股估值打击最大（高久期资产）。实际利率 = 名义利率 - 通胀预期。",
    relatedIndicators: ["名义10Y", "Breakeven通胀率", "纳斯达克"],
    fredCode: "DFII10",
    akshareFunc: null,
  },
  // ===================================================================
  //  美国 · 美元/风险偏好
  // ===================================================================
  {
    category: "美国 · 美元",
    id: "dxy",
    name: "美元指数 DXY",
    nameEn: "US Dollar Index (DXY)",
    definition: "衡量美元相对一篮子6种主要货币（欧元57.6%、日元13.6%、英镑11.9%、加元9.1%、瑞典克朗4.2%、瑞士法郎3.6%）的加权价值。DXY上升 = 美元走强。",
    unit: "指数",
    range: "近年 90–115",
    frequency: "日度（连续交易）",
    publishTime: "连续",
    source: "ICE Futures",
    sourceUrl: "https://www.ice.com/",
    methodology: "基于1973年3月的基期=100。几何加权平均。注意：不包含人民币，因此与USD/CNY走势不完全同步。",
    seasonalAdj: "无",
    revisionRisk: "无",
    signalRule: "<98 → 绿（利好新兴市场）| 98–103 → 黄 | >105 → 红",
    caveats: "DXY篮子不含人民币，反映的主要是美元vs欧元日元等发达货币关系。FRED的Broad Dollar Index（DTWEXBGS）覆盖更广。",
    relatedIndicators: ["USD/CNY", "EUR/USD", "Fed利率", "美国CPI"],
    fredCode: "DTWEXBGS (Broad Dollar proxy)",
    akshareFunc: null,
  },
  {
    category: "美国 · 风险偏好",
    id: "vix",
    name: "VIX 波动率指数",
    nameEn: "CBOE Volatility Index (VIX)",
    definition: "芝加哥期权交易所（CBOE）编制的标普500指数30天隐含波动率指数。被称为「恐慌指数」，反映市场对未来短期波动的预期。VIX上升 = 市场恐慌/不确定性增加。",
    unit: "点",
    range: "低波 <15 | 正常 15–20 | 偏高 20–28 | 恐慌 >30",
    frequency: "日度（连续交易）",
    publishTime: "连续",
    source: "CBOE / FRED",
    sourceUrl: "https://fred.stlouisfed.org/series/VIXCLS",
    methodology: "基于S&P 500指数期权（SPX）的加权隐含波动率计算，覆盖近月和次月的虚值看涨/看跌期权。",
    seasonalAdj: "无",
    revisionRisk: "无",
    signalRule: "<18 → 绿 | 18–25 → 黄 | >28 → 红 | 极低(<12)也是风险信号（complacency）",
    caveats: "VIX是前瞻性指标（预期而非实际波动率）。VIX飙升后常伴随市场反弹（均值回复特性）。需注意VIX期货曲线形态（contango/backwardation）。",
    relatedIndicators: ["S&P 500", "Put/Call比率", "MOVE指数（债市波动率）"],
    fredCode: "VIXCLS",
    akshareFunc: null,
  },
  {
    category: "美国 · 信用",
    id: "us_hy_spread",
    name: "美国高收益信用利差",
    nameEn: "US High Yield OAS (Option-Adjusted Spread)",
    definition: "ICE BofA美国高收益债券指数的期权调整利差。衡量高收益（垃圾级）企业债相对于国债的溢价。利差扩大 = 信用风险预期上升 = 市场risk-off。",
    unit: "% 或 bp",
    range: "低位 <300bp | 正常 300–500bp | 偏高 500–800bp | 危机 >800bp",
    frequency: "日度",
    publishTime: "每日",
    source: "FRED",
    sourceUrl: "https://fred.stlouisfed.org/series/BAMLH0A0HYM2",
    methodology: "ICE BofA编制。计算每只成分债券的OAS（扣除内嵌期权价值后的利差），按市值加权。覆盖评级BB及以下的美元计价企业债。",
    seasonalAdj: "无",
    revisionRisk: "无",
    signalRule: "<300bp → 绿（但可能偏紧/complacent）| 300–500bp → 黄 | >500bp → 红",
    caveats: "当前~290bp处于历史低位（20年均值~490bp），市场可能未充分补偿信用风险。利差急剧走扩是经济衰退的早期信号。",
    relatedIndicators: ["IG信用利差", "VIX", "Fed利率", "违约率"],
    fredCode: "BAMLH0A0HYM2",
    akshareFunc: null,
  },
];

// Render glossary into the page
(function () {
  function renderGlossary() {
    const el = document.getElementById("glossaryBlock");
    if (!el || !window.GLOSSARY) return;

    const glossary = window.GLOSSARY;
    const categories = [...new Set(glossary.map((g) => g.category))];

    let html = `
      <div style="margin-bottom:1.5rem;">
        <input type="text" id="glossarySearch" placeholder="搜索指标名称或关键词..."
          style="width:100%;padding:10px 16px;background:var(--bg1,#12151c);border:1px solid var(--line,rgba(232,220,198,0.12));
          border-radius:8px;color:var(--text,#e8dcc6);font-family:var(--font-ui);font-size:0.9rem;outline:none;">
      </div>
    `;

    categories.forEach((cat) => {
      const items = glossary.filter((g) => g.category === cat);
      html += `<div class="glossary-category" style="margin-bottom:2rem;">`;
      html += `<h3 style="font-family:var(--font-serif);font-size:1.1rem;margin-bottom:1rem;color:var(--accent,#e8a54b);border-bottom:1px solid var(--line);padding-bottom:0.5rem;">${cat}</h3>`;

      items.forEach((item) => {
        html += `
        <details class="glossary-item" data-search="${item.name} ${item.nameEn} ${item.definition} ${item.category}" style="margin-bottom:0.75rem;background:var(--bg1,#12151c);border:1px solid var(--line);border-radius:10px;overflow:hidden;">
          <summary style="padding:12px 16px;cursor:pointer;display:flex;align-items:center;gap:10px;font-weight:600;font-size:0.95rem;">
            <span style="color:var(--accent);">▸</span>
            <span>${item.name}</span>
            <span style="color:var(--faint);font-size:0.8rem;font-weight:400;margin-left:auto;">${item.nameEn}</span>
          </summary>
          <div style="padding:0 16px 16px;font-size:0.85rem;line-height:1.8;color:var(--muted);">
            <table style="width:100%;border-collapse:collapse;">
              <tr><td style="width:100px;padding:4px 8px;color:var(--text);font-weight:500;vertical-align:top;">定义</td><td style="padding:4px 8px;">${item.definition}</td></tr>
              <tr><td style="padding:4px 8px;color:var(--text);font-weight:500;vertical-align:top;">单位</td><td style="padding:4px 8px;">${item.unit}</td></tr>
              <tr><td style="padding:4px 8px;color:var(--text);font-weight:500;vertical-align:top;">取值范围</td><td style="padding:4px 8px;">${item.range}</td></tr>
              <tr><td style="padding:4px 8px;color:var(--text);font-weight:500;vertical-align:top;">频率</td><td style="padding:4px 8px;">${item.frequency}</td></tr>
              <tr><td style="padding:4px 8px;color:var(--text);font-weight:500;vertical-align:top;">发布时间</td><td style="padding:4px 8px;">${item.publishTime}</td></tr>
              <tr><td style="padding:4px 8px;color:var(--text);font-weight:500;vertical-align:top;">来源</td><td style="padding:4px 8px;"><a href="${item.sourceUrl}" target="_blank" style="color:var(--accent);">${item.source}</a></td></tr>
              <tr><td style="padding:4px 8px;color:var(--text);font-weight:500;vertical-align:top;">编制方法</td><td style="padding:4px 8px;">${item.methodology}</td></tr>
              <tr><td style="padding:4px 8px;color:var(--text);font-weight:500;vertical-align:top;">季节调整</td><td style="padding:4px 8px;">${item.seasonalAdj}</td></tr>
              <tr><td style="padding:4px 8px;color:var(--text);font-weight:500;vertical-align:top;">修订风险</td><td style="padding:4px 8px;">${item.revisionRisk}</td></tr>
              <tr><td style="padding:4px 8px;color:var(--text);font-weight:500;vertical-align:top;">信号规则</td><td style="padding:4px 8px;color:var(--text);">${item.signalRule}</td></tr>
              <tr><td style="padding:4px 8px;color:var(--text);font-weight:500;vertical-align:top;">注意事项</td><td style="padding:4px 8px;color:var(--yellow,#e8c547);">${item.caveats}</td></tr>
              <tr><td style="padding:4px 8px;color:var(--text);font-weight:500;vertical-align:top;">相关指标</td><td style="padding:4px 8px;">${item.relatedIndicators.join("、")}</td></tr>
              ${item.fredCode ? `<tr><td style="padding:4px 8px;color:var(--text);font-weight:500;vertical-align:top;">FRED代码</td><td style="padding:4px 8px;font-family:var(--font-mono);"><a href="https://fred.stlouisfed.org/series/${item.fredCode}" target="_blank" style="color:var(--accent);">${item.fredCode}</a></td></tr>` : ''}
              ${item.akshareFunc ? `<tr><td style="padding:4px 8px;color:var(--text);font-weight:500;vertical-align:top;">AKShare函数</td><td style="padding:4px 8px;font-family:var(--font-mono);">${item.akshareFunc}</td></tr>` : ''}
            </table>
          </div>
        </details>`;
      });

      html += `</div>`;
    });

    el.innerHTML = html;

    // Search functionality
    const searchInput = document.getElementById("glossarySearch");
    if (searchInput) {
      searchInput.addEventListener("input", function () {
        const query = this.value.toLowerCase();
        document.querySelectorAll(".glossary-item").forEach((item) => {
          const text = item.getAttribute("data-search").toLowerCase();
          item.style.display = text.includes(query) ? "" : "none";
        });
      });
    }
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", renderGlossary);
  } else {
    renderGlossary();
  }
})();
